# -*- coding: utf-8 -*-
"""Description en une ligne (FR) des mods qui comptent pour le gameplay."""
FR = {
 'apotheosis': "Loot à raretés, affixes et sockets ; enchantement apothique (étagères) ; boss apothiques. Cœur du système d'équipement.",
 'apothiccurios': "Permet aux accessoires (Curios) d'avoir des affixes et des sockets.",
 'apotheotic_additions': "Ajoute des centaines d'affixes, de joyaux, d'ensembles et de boss pour Apotheosis (dont la rareté « Ancien »).",
 'apothsb': "Compatibilité gemmes Apotheosis / sacs à dos.",
 'skilltree': "L'arbre de talents (588 nœuds, 6 classes), gemmes de l'arbre, parchemins de sagesse.",
 'autoleveling': "Les monstres montent en niveau selon la distance au spawn, la profondeur et la dimension.",
 'attributefix': "Relève les plafonds des attributs (vie, armure, puissance de sorts…).",
 'maxhealthfix': "Corrige le bug des plus de 20 cœurs.",
 'armordamagelimit': "Limite l'usure d'armure par coup.",
 'infernalmobs': "Monstres « infernaux » à pouvoirs aléatoires (style Diablo) qui lâchent du bon butin.",
 'xpbook': "Livre qui stocke de l'XP (XP Tome).",
 'origins': "Les origines (races) avec capacités passives et actives.",
 'origins_classes': "Les classes (guerrier, archer, forgeron…) : petits bonus de métier.",
 'strictly_origins': "Ajoute 15 origines (Paladin, Chevalier, Loutre, Voleur, Orc Chaman…).",
 'collectionofsingiro': "Collection d'origines supplémentaires (Medieval Origins, Arkwys…), souvent masquées par le pack.",
 'oriacs': "Origins: Accessibilities — ajoute des pouvoirs pratiques aux origines.",
 'irons_spellbooks': "Magie à mana : 89 sorts en 8 écoles, livres de sorts, parchemins, encres, armures de mage.",
 'ars_nouveau': "Magie à Source : on construit ses sorts avec des glyphes ; starbuncles, golems.",
 'ars_elemental': "Extension d'Ars : écoles élémentaires, armures et focus.",
 'ars_additions': "Petits ajouts et confort pour Ars Nouveau.",
 'toomanyglyphs': "Plus de glyphes pour Ars Nouveau.",
 'forbidden_arcanus': "Magie interdite : Hephaestus Forge, rituels, armures, objets aux pouvoirs sombres.",
 'bettercombat': "Combat à la Minecraft Dungeons : coups enchaînés, portée, animations.",
 'combatroll': "Roulade d'esquive (touche R).",
 'simplyswords': "Des dizaines d'épées légendaires à pouvoirs uniques.",
 'celestisynth': "Armes célestes aux compétences spectaculaires.",
 'iter_rpg': "Armures, armes, monstres et structures RPG semi-vanilla (donjons, boss, ensembles).",
 'cisco_mod': "Le contenu maison de Cisco : armures divines, épées légendaires, talismans, boss Cisco et Fell King.",
 'ciscounbound': "Version « unbound » du contenu de Cisco (même contenu, sans restrictions).",
 'dreadsteel': "Métal Dreadsteel : armure et armes très puissantes (immunité à plusieurs dégâts).",
 'upgradednetherite': "Améliore la netherite en plusieurs niveaux (Ultimerite…).",
 'immersive_armors': "Beaucoup de sets d'armure à l'apparence soignée.",
 'mcsa': "Armures de Minecraft Story Mode.",
 'majruszsenchantments': "Enchantements uniques et équilibrés.",
 'dragonenchants': "Enchantements inspirés des dragons.",
 'pehkui': "Redimensionne les entités (taille des origines).",
 'curios': "API des emplacements d'accessoires (anneaux, collier, ceinture…).",
 'relics': "Reliques à pouvoirs actifs et niveaux (Magic Mirror, Rage Glove…).",
 'enigmaticlegacy': "Anneaux, amulettes et objets maudits puissants ; Enigmas.",
 'enigmaticaddons': "Extension d'Enigmatic Legacy.",
 'majruszsaccessories': "Accessoires variés.",
 'ringsofascension': "Plus de 20 anneaux à effets.",
 'elytraslot': "Un emplacement dédié aux élytres.",
 'transmog': "Change l'apparence des objets sans changer leurs stats.",
 'gamestages': "Étapes de progression (framework).",
 'itemstages': "Verrouille des objets derrière une étape de progression.",
 'gateways': "Portails qui invoquent des vagues de monstres (Gate Pearls).",
 'progressivebosses': "Wither, dragon et Elder Guardian plus difficiles à chaque invocation.",
 'brutalbosses': "Pouvoirs supplémentaires pour les boss.",
 'raided': "Raids de pillards plus poussés.",
 'ftbquests': "Le livre de quêtes (la progression du pack).",
 'majruszsdifficulty': "Difficulté progressive : normal → expert → maître selon les dimensions.",
 'cataclysm': "Boss majeurs : Ignis, Leviathan, Harbinger, Ancient Remnant… avec plafonds de dégâts.",
 'bosses_of_mass_destruction': "Boss : Night Lich, Obsidilith, Nether Gauntlet, Void Blossom.",
 'meetyourfight': "Boss de palier 1 : Swampjaw, Bell Ringer, Dame Fortuna, Rosalyne…",
 'mowziesmobs': "Boss : Frostmaw, Umvuthi, Ferrous Wroughtnaut.",
 'alexsmobs': "Nombreux animaux et monstres originaux ; Void Worm, Warped Mosco.",
 'mutantmonsters': "Versions mutantes de monstres vanilla.",
 'undead_unleashed': "Morts-vivants à pouvoirs.",
 'enemyexpansion': "Nouveaux ennemis (gobelins, etc.).",
 'royalvariations': "Variantes « royales » de monstres (squelette roi, creeper roi).",
 'savage_and_ravage': "Illagers étendus, structures, créatures.",
 'sons_of_sins': "Les 7 péchés capitaux comme boss.",
 'whisperwoods': "Forêts hantées, boss Hirchgeist.",
 'dummmmmmy': "Mannequin d'entraînement qui affiche les dégâts.",
 'twilightforest': "Dimension de la forêt crépusculaire et ses boss (Naga, Lich, Hydra…).",
 'aether': "Dimension de l'Aether et ses donjons.",
 'deep_aether': "Extension de l'Aether.",
 'blue_skies': "Deux dimensions (Everbright / Everdawn) et leurs boss.",
 'byg': "Plus de 80 biomes.", 'atmospheric': "Biomes tropicaux et dunes.", 'incendium': "Refonte du Nether (biomes, structures, monstres).",
 'bygonenether': "Vestiges du passé du Nether.", 'deeperdarker': "Abysses étendus et Warden.", 'galosphere': "Nouvelles cavernes de cristaux.",
 'darkerdepths': "Cavernes étendues.", 'phantasm': "Refonte de l'End.", 'unusualend': "Extension de l'End (Endstone Golem…).",
 'endrem': "End Remastered : 12 yeux à trouver pour ouvrir le portail de l'End.", 'aquamirae': "Cimetière de navires et monstres des profondeurs.",
 'endlessbiomes': "Biomes de l'End.",
 'dungeon_crawl': "Donjons à la Roguelike.", 'dungeons_arise': "Structures et donjons spectaculaires.", 'knightquest': "Quêtes de chevaliers, ennemis et armures à thème.",
 'tlc': "Un immense château à explorer.",
 'minecolonies': "Fonder et gérer une colonie de villageois.", 'structurize': "Copier/coller des bâtiments.", 'domum_ornamentum': "Blocs décoratifs de MineColonies.",
 'easy_villagers': "Fermes de villageois.", 'goblintraders': "Marchands gobelins.", 'humancompanions': "Compagnons humains.", 'morevillagers': "Nouveaux métiers de villageois.",
 'towntalk': "Plus de répliques pour MineColonies.", 'betterwithminecolonies': "Corrige des recettes pour MineColonies.", 'stylecolonies': "Styles de bâtiments pour MineColonies.",
 'farmersdelight': "Cuisine et agriculture.", 'farmersrespite': "Thés et tisanes.", 'brewinandchewin': "Fermentation (vins, bières, fromages).", 'nethersdelight': "Cuisine du Nether.",
 'bakery': "Pain et pâtisseries.", 'vinery': "Vigne et vin.", 'delightful': "Extensions pour Farmer's Delight.", 'alexsdelight': "Cuisine avec les animaux d'Alex.",
 'solapplepie': "Diversité alimentaire : plus tu manges varié, plus tu gagnes de bonus permanents.", 'aquaculture': "Pêche étendue.", 'rightclickharvest': "Récolte en un clic droit.",
 'sophisticatedbackpacks': "Sacs à dos améliorables.", 'toms_storage': "Réseau de stockage avec terminal.", 'storagedrawers': "Tiroirs de stockage.", 'ironchest': "Gros coffres.",
 'waystones': "Téléportation entre pierres.", 'ftbchunks': "Revendication de terrain + carte.", 'ftbultimine': "Casse plusieurs blocs d'un coup.", 'lootr': "Coffres de butin individuels par joueur.",
 'corpse': "Cadavre à ta mort contenant ton inventaire.", 'carryon': "Porter coffres et animaux.", 'constructionwand': "Baguettes de construction.", 'smallships': "Bateaux.",
 'mythicmounts': "Montures mythiques.", 'comforts': "Sacs de couchage et hamacs.", 'ironfurnaces': "Fours en métal.",
}

FR.update({
 'clumps': "Regroupe les orbes d'XP (moins de lag).", 'corpsecurioscompat': "Les accessoires Curios sont aussi stockés dans le cadavre.", 'elevatorid': "Ascenseurs.",
 'sophisticatedcore': "Bibliothèque des sacs à dos.", 'upgradednetherite_items': "Objets de la netherite améliorée.", 'upgradednetherite_ultimate': "Niveau « Ultimerite » de la netherite.",
 'blockui': "Bibliothèque d'interface de MineColonies.", 'dungeons_arise_seven_seas': "Navires perdus sur les mers.", 'dungeoncrawl': "Donjons à la Roguelike.",
})
STRUCT = ['explorify', 'hoporp', 'skyvillages', 'structory', 'structorytowers', 't_and_t', 'wabi_sabi_structures', 'betterdeserttemples', 'betterdungeons', 'betterendisland', 'betterjungletemples',
          'bettermineshafts', 'betterfortresses', 'betteroceanmonuments', 'betterstrongholds', 'awesomedungeonend', 'awesomedungeonnether', 'ctov', 'dungeons_andtaverns_mr', 'dungeons_enhanced',
          'dungeons_plus', 'repurposed_structures', 'stalwart_dungeons', 'takesapillage', 'totw_modded']
for m in STRUCT: FR.setdefault(m, "Structures / donjons / villages supplémentaires à explorer (coffres de loot).")
