modLoader="javafml"
loaderVersion="[43,)"
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/CERBON-MODS/Bosses-of-Mass-Destruction-FORGE/issues"

[[mods]]
modId="bosses_of_mass_destruction"
version="1.0.6"
displayName="Bosses of Mass Destruction"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction-forge"
logoFile="icon.png"
credits="The original mod was created by Barribob for fabric."
authors="CerbonXD"
description='''Adds high threat mobs for players to take on.'''

[[dependencies.bosses_of_mass_destruction]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bosses_of_mass_destruction]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bosses_of_mass_destruction]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.1.40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bosses_of_mass_destruction]]
    modId="cloth_config"
    mandatory=true
    versionRange="[8.3.103,)"
    ordering="NONE"
    side="BOTH"

#[features.bosses_of_mass_destruction]
#openGLVersion="[3.2,)"