package com.github.L_Ender.cataclysm.client.model.entity;

import com.github.L_Ender.cataclysm.entity.AnimationMonster.BossMonsters.Amethyst_Crab_Entity;
import com.github.L_Ender.lionfishapi.client.model.Animations.ModelAnimator;
import com.github.L_Ender.lionfishapi.client.model.tools.AdvancedEntityModel;
import com.github.L_Ender.lionfishapi.client.model.tools.AdvancedModelBox;
import com.github.L_Ender.lionfishapi.client.model.tools.BasicModelPart;
import com.google.common.collect.ImmutableList;

public class Amethyst_Crab_Model extends AdvancedEntityModel<Amethyst_Crab_Entity> {
   private final AdvancedModelBox root;
   private final AdvancedModelBox body;
   private final AdvancedModelBox big_amethyst;
   private final AdvancedModelBox small_amethyst;
   private final AdvancedModelBox small_amethyst2;
   private final AdvancedModelBox amethyst_1;
   private final AdvancedModelBox small_amethyst3;
   private final AdvancedModelBox small_amethyst4;
   private final AdvancedModelBox left_body;
   private final AdvancedModelBox big_amethyst2;
   private final AdvancedModelBox right_body;
   private final AdvancedModelBox stomach;
   private final AdvancedModelBox head;
   private final AdvancedModelBox left_eye;
   private final AdvancedModelBox right_eye;
   private final AdvancedModelBox small_amethyst5;
   private final AdvancedModelBox small_amethyst6;
   private final AdvancedModelBox left_leg;
   private final AdvancedModelBox left_joint;
   private final AdvancedModelBox right_leg;
   private final AdvancedModelBox right_joint;
   private final AdvancedModelBox left_leg2;
   private final AdvancedModelBox left_joint2;
   private final AdvancedModelBox right_leg2;
   private final AdvancedModelBox right_joint2;
   private final AdvancedModelBox left_leg3;
   private final AdvancedModelBox left_joint3;
   private final AdvancedModelBox right_leg3;
   private final AdvancedModelBox right_joint3;
   private final AdvancedModelBox right_leg4;
   private final AdvancedModelBox left_leg4;
   private final AdvancedModelBox right_tong_leg;
   private final AdvancedModelBox right_Tong;
   private final AdvancedModelBox upper_claw2;
   private final AdvancedModelBox under_claw2;
   private final AdvancedModelBox left_tong_leg;
   private final AdvancedModelBox left_Tong;
   private final AdvancedModelBox upper_claw;
   private final AdvancedModelBox under_claw;
   private ModelAnimator animator;

   public Amethyst_Crab_Model() {
      this.texWidth = 256;
      this.texHeight = 256;
      this.root = new AdvancedModelBox(this);
      this.root.setRotationPoint(0.0F, 24.0F, 0.0F);
      this.body = new AdvancedModelBox(this);
      this.body.setRotationPoint(-0.4889F, -19.1765F, 3.4113F);
      this.root.addChild(this.body);
      this.setRotationAngle(this.body, -0.48F, 0.0F, 0.0F);
      this.body.setTextureOffset(0, 0).addBox(-7.5111F, -8.8235F, -18.4113F, 16.0F, 10.0F, 32.0F, 0.0F, false);
      this.body.setTextureOffset(0, 139).addBox(-6.5111F, -22.8235F, 0.5887F, 14.0F, 14.0F, 13.0F, 0.0F, false);
      this.big_amethyst = new AdvancedModelBox(this);
      this.big_amethyst.setRotationPoint(-8.0111F, -19.3235F, 5.0887F);
      this.body.addChild(this.big_amethyst);
      this.setRotationAngle(this.big_amethyst, 0.0F, 0.2182F, 0.0F);
      this.big_amethyst.setTextureOffset(0, 138).addBox(-6.5F, -11.5F, -6.5F, 13.0F, 24.0F, 14.0F, 0.0F, false);
      this.small_amethyst = new AdvancedModelBox(this);
      this.small_amethyst.setRotationPoint(0.0F, -11.5F, 0.5F);
      this.big_amethyst.addChild(this.small_amethyst);
      this.setRotationAngle(this.small_amethyst, 0.0F, 0.7854F, 0.0F);
      this.small_amethyst.setTextureOffset(71, 90).addBox(-5.5F, -10.0F, 0.0F, 11.0F, 10.0F, 0.0F, 0.0F, false);
      this.small_amethyst2 = new AdvancedModelBox(this);
      this.small_amethyst2.setRotationPoint(0.0F, -11.5F, 0.5F);
      this.big_amethyst.addChild(this.small_amethyst2);
      this.setRotationAngle(this.small_amethyst2, 0.0F, -0.7854F, 0.0F);
      this.small_amethyst2.setTextureOffset(132, 60).addBox(-5.5F, -10.0F, 0.0F, 11.0F, 10.0F, 0.0F, 0.0F, false);
      this.amethyst_1 = new AdvancedModelBox(this);
      this.amethyst_1.setRotationPoint(-8.0111F, -10.3235F, 0.5887F);
      this.body.addChild(this.amethyst_1);
      this.setRotationAngle(this.amethyst_1, 0.0F, 0.2182F, 0.0F);
      this.amethyst_1.setTextureOffset(102, 126).addBox(-7.5F, -5.5F, -11.0F, 9.0F, 9.0F, 9.0F, 0.0F, false);
      this.small_amethyst3 = new AdvancedModelBox(this);
      this.small_amethyst3.setRotationPoint(-3.0F, -5.5F, -7.0F);
      this.amethyst_1.addChild(this.small_amethyst3);
      this.setRotationAngle(this.small_amethyst3, 0.0F, -0.7854F, 0.0F);
      this.small_amethyst3.setTextureOffset(144, 29).addBox(-5.5F, -10.0F, 0.0F, 11.0F, 10.0F, 0.0F, 0.0F, false);
      this.small_amethyst4 = new AdvancedModelBox(this);
      this.small_amethyst4.setRotationPoint(-3.0F, -5.5F, -7.0F);
      this.amethyst_1.addChild(this.small_amethyst4);
      this.setRotationAngle(this.small_amethyst4, 0.0F, 0.7854F, 0.0F);
      this.small_amethyst4.setTextureOffset(144, 29).addBox(-5.5F, -10.0F, 0.0F, 11.0F, 10.0F, 0.0F, 0.0F, false);
      this.left_body = new AdvancedModelBox(this);
      this.left_body.setRotationPoint(8.9889F, -0.3235F, 0.0887F);
      this.body.addChild(this.left_body);
      this.setRotationAngle(this.left_body, -0.0289F, -0.2163F, 0.134F);
      this.left_body.setTextureOffset(0, 73).addBox(-5.5F, -3.5F, -16.5F, 21.0F, 0.0F, 28.0F, 0.0F, false);
      this.left_body.setTextureOffset(0, 102).addBox(-4.5F, -7.5F, -15.5F, 13.0F, 8.0F, 27.0F, 0.0F, false);
      this.big_amethyst2 = new AdvancedModelBox(this);
      this.big_amethyst2.setRotationPoint(6.5F, -7.5F, 4.0F);
      this.left_body.addChild(this.big_amethyst2);
      this.setRotationAngle(this.big_amethyst2, 0.0F, 0.0F, -0.1309F);
      this.big_amethyst2.setTextureOffset(101, 60).addBox(-8.0F, -4.0F, -10.5F, 7.0F, 4.0F, 8.0F, 0.0F, false);
      this.big_amethyst2.setTextureOffset(92, 159).addBox(-8.0F, -8.0F, -2.5F, 8.0F, 8.0F, 9.0F, 0.0F, false);
      this.right_body = new AdvancedModelBox(this);
      this.right_body.setRotationPoint(-8.0111F, -0.3235F, 0.0887F);
      this.body.addChild(this.right_body);
      this.setRotationAngle(this.right_body, -0.0289F, 0.2163F, -0.134F);
      this.right_body.setTextureOffset(65, 0).addBox(-16.5F, -3.5F, -16.5F, 21.0F, 0.0F, 28.0F, 0.0F, false);
      this.right_body.setTextureOffset(72, 90).addBox(-8.5F, -7.5F, -15.5F, 13.0F, 8.0F, 27.0F, 0.0F, false);
      this.stomach = new AdvancedModelBox(this);
      this.stomach.setRotationPoint(0.4889F, 2.6765F, 0.0887F);
      this.body.addChild(this.stomach);
      this.setRotationAngle(this.stomach, 0.0873F, 0.0F, 0.0F);
      this.stomach.setTextureOffset(0, 43).addBox(-14.0F, -4.5F, -13.5F, 28.0F, 7.0F, 22.0F, 0.0F, false);
      this.head = new AdvancedModelBox(this);
      this.head.setRotationPoint(0.4889F, 7.1765F, -19.4113F);
      this.body.addChild(this.head);
      this.left_eye = new AdvancedModelBox(this);
      this.left_eye.setRotationPoint(4.5F, -11.5F, 1.0F);
      this.head.addChild(this.left_eye);
      this.setRotationAngle(this.left_eye, 0.5672F, -0.2618F, 0.3491F);
      this.left_eye.setTextureOffset(71, 73).addBox(-0.5F, -9.5F, -2.0F, 3.0F, 9.0F, 2.0F, 0.0F, false);
      this.right_eye = new AdvancedModelBox(this);
      this.right_eye.setRotationPoint(-4.5F, -13.5F, 1.0F);
      this.head.addChild(this.right_eye);
      this.setRotationAngle(this.right_eye, 0.5672F, 0.2618F, -0.3491F);
      this.right_eye.setTextureOffset(14, 73).addBox(-2.5F, -7.5F, -2.0F, 3.0F, 9.0F, 2.0F, 0.0F, false);
      this.small_amethyst5 = new AdvancedModelBox(this);
      this.small_amethyst5.setRotationPoint(2.9889F, -26.8235F, 5.5887F);
      this.body.addChild(this.small_amethyst5);
      this.setRotationAngle(this.small_amethyst5, 0.0F, 0.7854F, 0.0F);
      this.small_amethyst5.setTextureOffset(0, 118).addBox(-5.5F, -6.0F, 0.0F, 11.0F, 10.0F, 0.0F, 0.0F, false);
      this.small_amethyst6 = new AdvancedModelBox(this);
      this.small_amethyst6.setRotationPoint(2.9889F, -21.8235F, 5.5887F);
      this.body.addChild(this.small_amethyst6);
      this.setRotationAngle(this.small_amethyst6, 0.0F, -0.7854F, 0.0F);
      this.small_amethyst6.setTextureOffset(71, 90).addBox(-5.5F, -10.0F, 0.0F, 11.0F, 10.0F, 0.0F, 0.0F, false);
      this.left_tong_leg = new AdvancedModelBox(this);
      this.left_tong_leg.setRotationPoint(14.4889F, 4.1765F, -13.4113F);
      this.body.addChild(this.left_tong_leg);
      this.setRotationAngle(this.left_tong_leg, 0.6545F, -0.7418F, 0.0F);
      this.left_tong_leg.setTextureOffset(136, 0).addBox(-4.0F, -3.0F, -16.0F, 8.0F, 7.0F, 20.0F, 0.0F, false);
      this.left_tong_leg.setTextureOffset(153, 90).addBox(0.0F, -9.0F, -16.0F, 0.0F, 13.0F, 20.0F, 0.0F, false);
      this.left_Tong = new AdvancedModelBox(this);
      this.left_Tong.setRotationPoint(0.0F, 0.5F, -14.5F);
      this.left_tong_leg.addChild(this.left_Tong);
      this.setRotationAngle(this.left_Tong, 0.0F, 1.1781F, 0.0F);
      this.left_Tong.setTextureOffset(55, 159).addBox(-3.0F, -6.5F, -11.0F, 6.0F, 13.0F, 12.0F, 0.0F, false);
      this.upper_claw = new AdvancedModelBox(this);
      this.upper_claw.setRotationPoint(0.0F, 1.0F, -11.0F);
      this.left_Tong.addChild(this.upper_claw);
      this.setRotationAngle(this.upper_claw, -0.4363F, 0.0F, 0.0F);
      this.upper_claw.setTextureOffset(0, 43).addBox(-2.0F, -21.5F, -6.0F, 4.0F, 10.0F, 4.0F, 0.0F, false);
      this.upper_claw.setTextureOffset(54, 114).addBox(-3.0F, -14.5F, -5.0F, 4.0F, 3.0F, 4.0F, 0.0F, false);
      this.upper_claw.setTextureOffset(0, 73).addBox(0.0F, -17.5F, -7.0F, 3.0F, 6.0F, 3.0F, 0.0F, false);
      this.upper_claw.setTextureOffset(79, 102).addBox(-2.0F, -16.5F, -12.0F, 4.0F, 5.0F, 4.0F, 0.0F, false);
      this.upper_claw.setTextureOffset(122, 126).addBox(-5.0F, -11.5F, -20.0F, 10.0F, 12.0F, 20.0F, 0.3F, false);
      this.upper_claw.setTextureOffset(61, 126).addBox(-5.0F, -11.5F, -20.0F, 10.0F, 12.0F, 20.0F, 0.0F, false);
      this.under_claw = new AdvancedModelBox(this);
      this.under_claw.setRotationPoint(0.0F, 1.5F, -11.0F);
      this.left_Tong.addChild(this.under_claw);
      this.setRotationAngle(this.under_claw, 0.5236F, 0.0F, 0.0F);
      this.under_claw.setTextureOffset(158, 60).addBox(-4.0F, 0.0F, -17.0F, 8.0F, 5.0F, 17.0F, 0.0F, false);
      this.right_tong_leg = new AdvancedModelBox(this);
      this.right_tong_leg.setRotationPoint(-10.5111F, 6.1765F, -11.4113F);
      this.body.addChild(this.right_tong_leg);
      this.setRotationAngle(this.right_tong_leg, 0.3927F, 0.5236F, -0.0873F);
      this.right_tong_leg.setTextureOffset(126, 90).addBox(-3.8F, -2.5F, -13.0F, 6.0F, 4.0F, 13.0F, 0.0F, false);
      this.right_tong_leg.setTextureOffset(0, 73).addBox(-0.8F, -6.5F, -13.0F, 0.0F, 8.0F, 13.0F, 0.0F, false);
      this.right_Tong = new AdvancedModelBox(this);
      this.right_Tong.setRotationPoint(-1.0F, 0.0F, -13.0F);
      this.right_tong_leg.addChild(this.right_Tong);
      this.setRotationAngle(this.right_Tong, 0.0F, -1.1781F, 0.0F);
      this.right_Tong.setTextureOffset(0, 102).addBox(-1.8F, -3.5F, -4.0F, 4.0F, 6.0F, 9.0F, 0.0F, false);
      this.upper_claw2 = new AdvancedModelBox(this);
      this.upper_claw2.setRotationPoint(0.1F, 1.0F, -4.0F);
      this.right_Tong.addChild(this.upper_claw2);
      this.setRotationAngle(this.upper_claw2, -0.4363F, 0.0F, 0.0F);
      this.upper_claw2.setTextureOffset(127, 159).addBox(-2.9F, -6.5F, -10.0F, 6.0F, 7.0F, 10.0F, 0.0F, false);
      this.under_claw2 = new AdvancedModelBox(this);
      this.under_claw2.setRotationPoint(0.2F, 1.5F, -4.0F);
      this.right_Tong.addChild(this.under_claw2);
      this.setRotationAngle(this.under_claw2, 0.5672F, 0.0F, 0.0F);
      this.under_claw2.setTextureOffset(54, 102).addBox(-2.0F, 0.0F, -8.0F, 4.0F, 3.0F, 8.0F, 0.0F, false);
      this.left_leg = new AdvancedModelBox(this);
      this.left_leg.setRotationPoint(12.0F, -17.0F, -2.5F);
      this.root.addChild(this.left_leg);
      this.setRotationAngle(this.left_leg, -0.1309F, 0.6109F, -0.0873F);
      this.left_leg.setTextureOffset(97, 29).addBox(0.0F, -2.0F, -2.0F, 19.0F, 4.0F, 4.0F, 0.0F, false);
      this.left_joint = new AdvancedModelBox(this);
      this.left_joint.setRotationPoint(18.3F, -0.1F, 0.0F);
      this.left_leg.addChild(this.left_joint);
      this.setRotationAngle(this.left_joint, -0.1309F, 0.0F, 0.0F);
      this.left_joint.setTextureOffset(187, 28).addBox(-0.3F, -8.4F, 0.0F, 12.0F, 27.0F, 0.0F, 0.0F, false);
      this.left_joint.setTextureOffset(65, 0).addBox(-0.3F, -2.4F, -3.0F, 6.0F, 21.0F, 6.0F, 0.0F, false);
      this.right_leg = new AdvancedModelBox(this);
      this.right_leg.setRotationPoint(-12.0F, -17.0F, -2.5F);
      this.root.addChild(this.right_leg);
      this.setRotationAngle(this.right_leg, -0.1309F, -0.6109F, 0.0873F);
      this.right_leg.setTextureOffset(97, 29).addBox(-19.0F, -2.0F, -2.0F, 19.0F, 4.0F, 4.0F, 0.0F, true);
      this.right_joint = new AdvancedModelBox(this);
      this.right_joint.setRotationPoint(-18.3F, -0.1F, 0.0F);
      this.right_leg.addChild(this.right_joint);
      this.setRotationAngle(this.right_joint, -0.1309F, 0.0F, 0.0F);
      this.right_joint.setTextureOffset(0, 0).addBox(-11.7F, -8.4F, 0.0F, 12.0F, 27.0F, 0.0F, 0.0F, true);
      this.right_joint.setTextureOffset(65, 0).addBox(-5.7F, -2.4F, -3.0F, 6.0F, 21.0F, 6.0F, 0.0F, true);
      this.left_leg2 = new AdvancedModelBox(this);
      this.left_leg2.setRotationPoint(12.0F, -16.0F, 2.5F);
      this.root.addChild(this.left_leg2);
      this.setRotationAngle(this.left_leg2, 0.0F, 0.0F, -0.0873F);
      this.left_leg2.setTextureOffset(97, 29).addBox(0.0F, -2.0F, -2.0F, 19.0F, 4.0F, 4.0F, 0.0F, false);
      this.left_joint2 = new AdvancedModelBox(this);
      this.left_joint2.setRotationPoint(14.3F, 0.9F, 0.0F);
      this.left_leg2.addChild(this.left_joint2);
      this.setRotationAngle(this.left_joint2, -0.1309F, -0.0873F, -0.4363F);
      this.left_joint2.setTextureOffset(0, 0).addBox(-0.3F, -8.4F, 0.0F, 12.0F, 27.0F, 0.0F, 0.0F, false);
      this.left_joint2.setTextureOffset(66, 0).addBox(-0.3F, -2.4F, -3.0F, 6.0F, 21.0F, 6.0F, 0.0F, false);
      this.right_leg2 = new AdvancedModelBox(this);
      this.right_leg2.setRotationPoint(-12.0F, -16.0F, 2.5F);
      this.root.addChild(this.right_leg2);
      this.setRotationAngle(this.right_leg2, 0.0F, 0.0F, 0.0873F);
      this.right_leg2.setTextureOffset(97, 29).addBox(-19.0F, -2.0F, -2.0F, 19.0F, 4.0F, 4.0F, 0.0F, true);
      this.right_joint2 = new AdvancedModelBox(this);
      this.right_joint2.setRotationPoint(-14.3F, 0.9F, 0.0F);
      this.right_leg2.addChild(this.right_joint2);
      this.setRotationAngle(this.right_joint2, -0.1309F, 0.0873F, 0.4363F);
      this.right_joint2.setTextureOffset(187, 28).addBox(-11.7F, -8.4F, 0.0F, 12.0F, 27.0F, 0.0F, 0.0F, true);
      this.right_joint2.setTextureOffset(65, 0).addBox(-5.7F, -2.4F, -3.0F, 6.0F, 21.0F, 6.0F, 0.0F, true);
      this.left_leg3 = new AdvancedModelBox(this);
      this.left_leg3.setRotationPoint(12.0F, -13.0F, 9.5F);
      this.root.addChild(this.left_leg3);
      this.setRotationAngle(this.left_leg3, 0.2618F, -0.3927F, -0.2182F);
      this.left_leg3.setTextureOffset(97, 29).addBox(0.0F, -2.0F, -2.0F, 19.0F, 4.0F, 4.0F, 0.0F, false);
      this.left_joint3 = new AdvancedModelBox(this);
      this.left_joint3.setRotationPoint(14.3F, 0.9F, 0.0F);
      this.left_leg3.addChild(this.left_joint3);
      this.setRotationAngle(this.left_joint3, -0.1309F, -0.0873F, -0.3927F);
      this.left_joint3.setTextureOffset(187, 28).addBox(-0.3F, -8.4F, 0.0F, 12.0F, 27.0F, 0.0F, 0.0F, false);
      this.left_joint3.setTextureOffset(65, 0).addBox(-0.3F, -2.4F, -3.0F, 6.0F, 21.0F, 6.0F, 0.0F, false);
      this.right_leg3 = new AdvancedModelBox(this);
      this.right_leg3.setRotationPoint(-12.0F, -13.0F, 9.5F);
      this.root.addChild(this.right_leg3);
      this.setRotationAngle(this.right_leg3, 0.2618F, 0.3927F, 0.2182F);
      this.right_leg3.setTextureOffset(97, 29).addBox(-19.0F, -2.0F, -2.0F, 19.0F, 4.0F, 4.0F, 0.0F, true);
      this.right_joint3 = new AdvancedModelBox(this);
      this.right_joint3.setRotationPoint(-14.3F, 0.9F, 0.0F);
      this.right_leg3.addChild(this.right_joint3);
      this.setRotationAngle(this.right_joint3, -0.1309F, 0.0873F, 0.3927F);
      this.right_joint3.setTextureOffset(0, 0).addBox(-11.7F, -8.4F, 0.0F, 12.0F, 27.0F, 0.0F, 0.0F, true);
      this.right_joint3.setTextureOffset(65, 0).addBox(-5.7F, -2.4F, -3.0F, 6.0F, 21.0F, 6.0F, 0.0F, true);
      this.right_leg4 = new AdvancedModelBox(this);
      this.right_leg4.setRotationPoint(-10.5F, -15.0F, 14.5F);
      this.root.addChild(this.right_leg4);
      this.setRotationAngle(this.right_leg4, -0.576F, 0.6981F, -0.6109F);
      this.right_leg4.setTextureOffset(79, 43).addBox(-31.5F, 1.0F, -7.5F, 35.0F, 0.0F, 16.0F, 0.0F, false);
      this.left_leg4 = new AdvancedModelBox(this);
      this.left_leg4.setRotationPoint(10.5F, -15.0F, 14.5F);
      this.root.addChild(this.left_leg4);
      this.setRotationAngle(this.left_leg4, -0.6109F, -0.7418F, 0.6109F);
      this.left_leg4.setTextureOffset(71, 73).addBox(-3.5F, 1.0F, -7.5F, 35.0F, 0.0F, 16.0F, 0.0F, false);
      this.animator = ModelAnimator.create();
      this.updateDefaultPose();
   }

   public Iterable<AdvancedModelBox> getAllParts() {
      return ImmutableList.of(
         this.root,
         this.body,
         this.big_amethyst,
         this.small_amethyst,
         this.small_amethyst2,
         this.amethyst_1,
         this.small_amethyst3,
         this.small_amethyst4,
         this.left_body,
         this.big_amethyst2,
         this.right_body,
         this.stomach,
         new AdvancedModelBox[]{
            this.head,
            this.left_eye,
            this.right_eye,
            this.small_amethyst5,
            this.small_amethyst6,
            this.left_leg,
            this.left_joint,
            this.right_leg,
            this.left_joint2,
            this.left_leg2,
            this.right_joint,
            this.left_leg2,
            this.left_joint2,
            this.right_leg2,
            this.right_joint2,
            this.left_leg3,
            this.left_joint3,
            this.right_leg3,
            this.right_joint3,
            this.right_leg4,
            this.left_leg4,
            this.right_tong_leg,
            this.right_Tong,
            this.upper_claw2,
            this.under_claw2,
            this.left_tong_leg,
            this.left_Tong,
            this.upper_claw,
            this.under_claw
         }
      );
   }

   public Iterable<BasicModelPart> parts() {
      return ImmutableList.of(this.root);
   }

   public void animate(Amethyst_Crab_Entity entity, float f, float f1, float f2, float f3, float f4) {
      this.resetToDefaultPose();
      this.animator.update(entity);
      this.animator.setAnimation(Amethyst_Crab_Entity.CRAB_SMASH);
      this.animator.startKeyframe(12);
      this.animator.rotate(this.body, (float)Math.toRadians(5.0), 0.0F, (float)Math.toRadians(-5.0));
      this.animator.rotate(this.left_body, 0.0F, 0.0F, (float)Math.toRadians(-5.0));
      this.animator.rotate(this.right_body, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.left_joint, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.rotate(this.left_leg4, 0.0F, (float)Math.toRadians(7.5), 0.0F);
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(-5.0), 0.0F);
      this.animator.rotate(this.right_joint, 0.0F, 0.0F, (float)Math.toRadians(10.0));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.rotate(this.right_joint2, 0.0F, 0.0F, (float)Math.toRadians(-2.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.right_joint3, 0.0F, 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.right_leg4, (float)Math.toRadians(-15.0), (float)Math.toRadians(10.0), (float)Math.toRadians(-12.5));
      this.animator.rotate(this.right_tong_leg, 0.0F, (float)Math.toRadians(5.0), 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(5.0), 0.0F);
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-27.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(-60.0), (float)Math.toRadians(22.5), (float)Math.toRadians(20.0));
      this.animator.move(this.left_tong_leg, 0.0F, -4.0F, 0.0F);
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(-67.5), (float)Math.toRadians(-32.5), (float)Math.toRadians(-25.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(16.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-57.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(8);
      this.animator.startKeyframe(3);
      this.animator.move(this.root, 0.0F, 2.0F, 0.0F);
      this.animator.rotate(this.body, (float)Math.toRadians(40.0), (float)Math.toRadians(20.0), 0.0F);
      this.animator.rotate(this.left_body, 0.0F, 0.0F, (float)Math.toRadians(-5.0));
      this.animator.rotate(this.right_body, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(10.0));
      this.animator.rotate(this.left_joint, 0.0F, 0.0F, (float)Math.toRadians(-17.5));
      this.animator.rotate(this.left_leg4, (float)Math.toRadians(-12.5), 0.0F, (float)Math.toRadians(17.5));
      this.animator.move(this.left_leg4, 0.0F, -6.0F, 0.0F);
      this.animator.rotate(this.right_leg, (float)Math.toRadians(-20.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(-30.0));
      this.animator.rotate(this.right_joint, 0.0F, 0.0F, (float)Math.toRadians(57.5));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.rotate(this.right_joint2, 0.0F, 0.0F, (float)Math.toRadians(-20.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.right_joint3, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.rotate(this.right_leg4, (float)Math.toRadians(-25.0), 0.0F, (float)Math.toRadians(-22.5));
      this.animator.move(this.right_leg4, -3.0F, -7.0F, 0.0F);
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(-15.0), (float)Math.toRadians(-20.0), 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(30.0), 0.0F);
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-27.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(-47.5), (float)Math.toRadians(10.0), (float)Math.toRadians(10.0));
      this.animator.move(this.left_tong_leg, 0.0F, -4.0F, 0.0F);
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(80.0), (float)Math.toRadians(-57.5), (float)Math.toRadians(67.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(25.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(20);
      this.animator.resetKeyframe(10);
      this.animator.setAnimation(Amethyst_Crab_Entity.CRAB_SMASH_THREE);
      this.animator.startKeyframe(10);
      this.animator.rotate(this.body, (float)Math.toRadians(-27.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_body, 0.0F, 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.right_body, 0.0F, 0.0F, (float)Math.toRadians(10.0));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(-15.0));
      this.animator.rotate(this.left_joint, (float)Math.toRadians(12.5), 0.0F, (float)Math.toRadians(-12.5));
      this.animator.rotate(this.right_leg, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_joint, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_joint2, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.right_joint2, 0.0F, 0.0F, (float)Math.toRadians(-12.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.left_joint3, 0.0F, 0.0F, (float)Math.toRadians(22.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(7.5));
      this.animator.rotate(this.right_joint3, 0.0F, 0.0F, (float)Math.toRadians(-22.5));
      this.animator.rotate(this.left_leg4, (float)Math.toRadians(10.0), (float)Math.toRadians(-2.5), (float)Math.toRadians(-7.5));
      this.animator.rotate(this.right_leg4, (float)Math.toRadians(20.0), (float)Math.toRadians(15.0), (float)Math.toRadians(12.5));
      this.animator.move(this.right_leg4, 0.0F, 6.0F, 0.0F);
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(-32.5), (float)Math.toRadians(-25.0), (float)Math.toRadians(-30.0));
      this.animator.rotate(this.right_Tong, (float)Math.toRadians(12.5), (float)Math.toRadians(37.5), (float)Math.toRadians(-60.0));
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(22.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-22.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(-62.5), (float)Math.toRadians(25.0), (float)Math.toRadians(20.0));
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(42.5), (float)Math.toRadians(-20.0), (float)Math.toRadians(62.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(4);
      this.animator.startKeyframe(3);
      this.animator.move(this.root, 0.0F, 2.0F, 0.0F);
      this.animator.rotate(this.body, (float)Math.toRadians(55.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_body, 0.0F, 0.0F, (float)Math.toRadians(-2.5));
      this.animator.rotate(this.right_body, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(7.5));
      this.animator.rotate(this.left_joint, (float)Math.toRadians(17.5), 0.0F, (float)Math.toRadians(-17.5));
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(-7.5), (float)Math.toRadians(20.0));
      this.animator.move(this.right_leg, 0.0F, 7.0F, 0.0F);
      this.animator.rotate(this.right_joint, (float)Math.toRadians(12.5), 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(12.5));
      this.animator.rotate(this.left_joint2, 0.0F, 0.0F, (float)Math.toRadians(-17.5));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(-5.0));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(25.0));
      this.animator.move(this.left_leg3, 0.0F, -7.0F, 0.0F);
      this.animator.rotate(this.left_joint3, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-27.5));
      this.animator.move(this.right_leg3, 0.0F, -7.0F, 0.0F);
      this.animator.rotate(this.right_joint3, 0.0F, 0.0F, (float)Math.toRadians(10.0));
      this.animator.rotate(this.left_leg4, 0.0F, 0.0F, (float)Math.toRadians(22.5));
      this.animator.move(this.left_leg4, 0.0F, -8.0F, 0.0F);
      this.animator.rotate(this.right_leg4, 0.0F, 0.0F, (float)Math.toRadians(-25.0));
      this.animator.move(this.right_leg4, 0.0F, -7.0F, 0.0F);
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(-25.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(-5.0));
      this.animator.rotate(this.right_Tong, (float)Math.toRadians(17.5), (float)Math.toRadians(55.0), (float)Math.toRadians(-92.5));
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-35.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(-32.5), (float)Math.toRadians(30.0), (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(65.0), (float)Math.toRadians(-30.0), (float)Math.toRadians(92.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(27.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-37.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(3);
      this.animator.startKeyframe(10);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(32.5), 0.0F);
      this.animator.rotate(this.body, (float)Math.toRadians(-27.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_body, 0.0F, 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.right_body, 0.0F, 0.0F, (float)Math.toRadians(10.0));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(-15.0));
      this.animator.rotate(this.left_joint, (float)Math.toRadians(17.5), 0.0F, (float)Math.toRadians(-17.5));
      this.animator.rotate(this.right_leg, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_joint, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_joint2, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.right_joint2, 0.0F, 0.0F, (float)Math.toRadians(-12.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.left_joint3, 0.0F, 0.0F, (float)Math.toRadians(22.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(7.5));
      this.animator.rotate(this.right_joint3, 0.0F, 0.0F, (float)Math.toRadians(-22.5));
      this.animator.rotate(this.left_leg4, (float)Math.toRadians(10.0), (float)Math.toRadians(-2.5), (float)Math.toRadians(-7.5));
      this.animator.move(this.left_leg4, 0.0F, 4.0F, 0.0F);
      this.animator.rotate(this.right_leg4, (float)Math.toRadians(20.0), (float)Math.toRadians(15.0), (float)Math.toRadians(12.5));
      this.animator.move(this.right_leg4, 0.0F, 6.0F, 0.0F);
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(-32.5), (float)Math.toRadians(-25.0), (float)Math.toRadians(-30.0));
      this.animator.rotate(this.right_Tong, (float)Math.toRadians(17.5), (float)Math.toRadians(55.0), (float)Math.toRadians(-92.5));
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-35.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(-62.5), (float)Math.toRadians(25.0), (float)Math.toRadians(20.0));
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(65.0), (float)Math.toRadians(-30.0), (float)Math.toRadians(92.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(27.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-37.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(4);
      this.animator.startKeyframe(3);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(45.0), 0.0F);
      this.animator.move(this.root, 0.0F, 2.0F, 0.0F);
      this.animator.rotate(this.body, (float)Math.toRadians(55.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_body, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_body, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.rotate(this.left_joint, (float)Math.toRadians(17.5), 0.0F, (float)Math.toRadians(-17.5));
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(-7.5), (float)Math.toRadians(20.0));
      this.animator.move(this.right_leg, 0.0F, 7.0F, 0.0F);
      this.animator.rotate(this.right_joint, (float)Math.toRadians(12.5), 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(12.5));
      this.animator.rotate(this.left_joint2, 0.0F, 0.0F, (float)Math.toRadians(-17.5));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(-5.0));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(25.0));
      this.animator.move(this.left_leg3, 0.0F, -7.0F, 0.0F);
      this.animator.rotate(this.left_joint3, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-27.5));
      this.animator.move(this.right_leg3, 0.0F, -7.0F, 0.0F);
      this.animator.rotate(this.right_joint3, 0.0F, 0.0F, (float)Math.toRadians(10.0));
      this.animator.rotate(this.left_leg4, 0.0F, 0.0F, (float)Math.toRadians(22.5));
      this.animator.move(this.left_leg4, 0.0F, -8.0F, 0.0F);
      this.animator.rotate(this.right_leg4, 0.0F, 0.0F, (float)Math.toRadians(-25.0));
      this.animator.move(this.right_leg4, 0.0F, -7.0F, 0.0F);
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(-25.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(-5.0));
      this.animator.rotate(this.right_Tong, (float)Math.toRadians(20.0), (float)Math.toRadians(55.0), (float)Math.toRadians(-92.5));
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-35.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(-32.5), (float)Math.toRadians(30.0), (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(65.0), (float)Math.toRadians(-30.0), (float)Math.toRadians(92.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(27.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-37.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(3);
      this.animator.startKeyframe(10);
      this.animator.rotate(this.body, (float)Math.toRadians(-27.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_body, 0.0F, 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.right_body, 0.0F, 0.0F, (float)Math.toRadians(10.0));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(-15.0));
      this.animator.rotate(this.left_joint, (float)Math.toRadians(17.5), 0.0F, (float)Math.toRadians(-17.5));
      this.animator.rotate(this.right_leg, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_joint, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_joint2, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.right_joint2, 0.0F, 0.0F, (float)Math.toRadians(-12.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.left_joint3, 0.0F, 0.0F, (float)Math.toRadians(22.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(7.5));
      this.animator.rotate(this.right_joint3, 0.0F, 0.0F, (float)Math.toRadians(-22.5));
      this.animator.rotate(this.left_leg4, (float)Math.toRadians(10.0), (float)Math.toRadians(-2.5), (float)Math.toRadians(-7.5));
      this.animator.move(this.left_leg4, 0.0F, 4.0F, 0.0F);
      this.animator.rotate(this.right_leg4, (float)Math.toRadians(20.0), (float)Math.toRadians(15.0), (float)Math.toRadians(12.5));
      this.animator.move(this.right_leg4, 0.0F, 6.0F, 0.0F);
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(-35.0), (float)Math.toRadians(-25.0), (float)Math.toRadians(-30.0));
      this.animator.rotate(this.right_Tong, (float)Math.toRadians(17.5), (float)Math.toRadians(55.0), (float)Math.toRadians(-92.5));
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-35.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(-62.5), (float)Math.toRadians(25.0), (float)Math.toRadians(20.0));
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(65.0), (float)Math.toRadians(-30.0), (float)Math.toRadians(92.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(27.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-37.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(4);
      this.animator.startKeyframe(3);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(-25.0), 0.0F);
      this.animator.move(this.root, 0.0F, 2.0F, 0.0F);
      this.animator.rotate(this.body, (float)Math.toRadians(55.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_body, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_body, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(7.5));
      this.animator.rotate(this.left_joint, (float)Math.toRadians(17.5), 0.0F, (float)Math.toRadians(-17.5));
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(-7.5), (float)Math.toRadians(20.0));
      this.animator.move(this.right_leg, 0.0F, 7.0F, 0.0F);
      this.animator.rotate(this.right_joint, (float)Math.toRadians(12.5), 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(12.5));
      this.animator.rotate(this.left_joint2, 0.0F, 0.0F, (float)Math.toRadians(-17.5));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(-5.0));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(25.0));
      this.animator.move(this.left_leg3, 0.0F, -7.0F, 0.0F);
      this.animator.rotate(this.left_joint3, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-27.5));
      this.animator.move(this.right_leg3, 0.0F, -7.0F, 0.0F);
      this.animator.rotate(this.right_joint3, 0.0F, 0.0F, (float)Math.toRadians(10.0));
      this.animator.rotate(this.left_leg4, 0.0F, 0.0F, (float)Math.toRadians(22.5));
      this.animator.move(this.left_leg4, 0.0F, -8.0F, 0.0F);
      this.animator.rotate(this.right_leg4, 0.0F, 0.0F, (float)Math.toRadians(-25.0));
      this.animator.move(this.right_leg4, 0.0F, -7.0F, 0.0F);
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(-25.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(-5.0));
      this.animator.rotate(this.right_Tong, (float)Math.toRadians(20.0), (float)Math.toRadians(55.0), (float)Math.toRadians(-92.5));
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-35.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(-32.5), (float)Math.toRadians(30.0), (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(65.0), (float)Math.toRadians(-30.0), (float)Math.toRadians(92.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(27.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-37.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.resetKeyframe(10);
      this.animator.setAnimation(Amethyst_Crab_Entity.CRAB_DEATH);
      this.animator.startKeyframe(8);
      this.animator.rotate(this.root, (float)Math.toRadians(-150.0), 0.0F, 0.0F);
      this.animator.move(this.root, 0.0F, -26.0F, -9.0F);
      this.animator.rotate(this.body, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_eye, 0.0F, 0.0F, (float)Math.toRadians(55.0));
      this.animator.rotate(this.right_eye, 0.0F, 0.0F, (float)Math.toRadians(-62.5));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(45.0));
      this.animator.rotate(this.right_leg, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(32.5));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(-32.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-30.0));
      this.animator.rotate(this.right_leg4, 0.0F, 0.0F, (float)Math.toRadians(-20.0));
      this.animator.rotate(this.left_leg4, (float)Math.toRadians(-30.0), (float)Math.toRadians(27.5), (float)Math.toRadians(45.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, 0.0F, (float)Math.toRadians(-17.5), 0.0F);
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(-37.5), (float)Math.toRadians(-47.5), (float)Math.toRadians(-67.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-22.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(3);
      this.animator.rotate(this.root, (float)Math.toRadians(-150.0), 0.0F, 0.0F);
      this.animator.move(this.root, 0.0F, -26.0F, -9.0F);
      this.animator.rotate(this.body, (float)Math.toRadians(-2.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_eye, 0.0F, 0.0F, (float)Math.toRadians(55.0));
      this.animator.rotate(this.right_eye, 0.0F, 0.0F, (float)Math.toRadians(-62.5));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(27.5));
      this.animator.rotate(this.right_leg, 0.0F, 0.0F, (float)Math.toRadians(15.0));
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(15.0));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(-22.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-22.5));
      this.animator.rotate(this.right_leg4, 0.0F, (float)Math.toRadians(2.5), (float)Math.toRadians(-7.5));
      this.animator.rotate(this.left_leg4, (float)Math.toRadians(-22.5), (float)Math.toRadians(15.0), (float)Math.toRadians(35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(-17.5), 0.0F, 0.0F);
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, 0.0F, (float)Math.toRadians(-7.5), 0.0F);
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(-37.5), (float)Math.toRadians(-47.5), (float)Math.toRadians(-67.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(3);
      this.animator.rotate(this.root, (float)Math.toRadians(-150.0), (float)Math.toRadians(2.5), (float)Math.toRadians(1.25));
      this.animator.move(this.root, 0.0F, -25.0F, -9.0F);
      this.animator.rotate(this.body, (float)Math.toRadians(-2.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_eye, 0.0F, 0.0F, (float)Math.toRadians(55.0));
      this.animator.rotate(this.right_eye, 0.0F, 0.0F, (float)Math.toRadians(-62.5));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(62.5));
      this.animator.rotate(this.right_leg, 0.0F, 0.0F, (float)Math.toRadians(-32.5));
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(47.5));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(-42.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(42.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-37.5));
      this.animator.rotate(this.right_leg4, 0.0F, (float)Math.toRadians(7.5), (float)Math.toRadians(15.0));
      this.animator.rotate(this.left_leg4, (float)Math.toRadians(-7.5), (float)Math.toRadians(-12.5), (float)Math.toRadians(10.0));
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(-37.5), (float)Math.toRadians(-47.5), (float)Math.toRadians(-67.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(3);
      this.animator.rotate(this.root, (float)Math.toRadians(-150.0), (float)Math.toRadians(2.5), (float)Math.toRadians(1.25));
      this.animator.move(this.root, 0.0F, -25.0F, -9.0F);
      this.animator.rotate(this.left_eye, 0.0F, 0.0F, (float)Math.toRadians(55.0));
      this.animator.rotate(this.right_eye, 0.0F, 0.0F, (float)Math.toRadians(-62.5));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(62.5));
      this.animator.rotate(this.right_leg, 0.0F, 0.0F, (float)Math.toRadians(-32.5));
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(47.5));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(-42.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(42.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-37.5));
      this.animator.rotate(this.right_leg4, 0.0F, (float)Math.toRadians(2.5), (float)Math.toRadians(-7.5));
      this.animator.rotate(this.left_leg4, (float)Math.toRadians(-22.5), (float)Math.toRadians(15.0), (float)Math.toRadians(35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(-17.5), 0.0F, 0.0F);
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(-37.5), (float)Math.toRadians(-47.5), (float)Math.toRadians(-67.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-5.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(3);
      this.animator.rotate(this.root, (float)Math.toRadians(-150.0), (float)Math.toRadians(2.5), (float)Math.toRadians(1.25));
      this.animator.move(this.root, 0.0F, -25.0F, -9.0F);
      this.animator.rotate(this.left_eye, 0.0F, 0.0F, (float)Math.toRadians(55.0));
      this.animator.rotate(this.right_eye, 0.0F, 0.0F, (float)Math.toRadians(-62.5));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(27.5));
      this.animator.rotate(this.right_leg, 0.0F, 0.0F, (float)Math.toRadians(15.0));
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(15.0));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(-22.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-22.5));
      this.animator.rotate(this.right_leg4, 0.0F, (float)Math.toRadians(7.5), (float)Math.toRadians(15.0));
      this.animator.rotate(this.left_leg4, (float)Math.toRadians(-7.5), (float)Math.toRadians(-12.5), (float)Math.toRadians(10.0));
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, 0.0F, (float)Math.toRadians(-17.5), 0.0F);
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(-37.5), (float)Math.toRadians(-47.5), (float)Math.toRadians(-67.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(3);
      this.animator.rotate(this.root, (float)Math.toRadians(-150.0), (float)Math.toRadians(2.5), (float)Math.toRadians(1.25));
      this.animator.move(this.root, 0.0F, -25.0F, -9.0F);
      this.animator.rotate(this.left_eye, 0.0F, 0.0F, (float)Math.toRadians(55.0));
      this.animator.rotate(this.right_eye, 0.0F, 0.0F, (float)Math.toRadians(-62.5));
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(50.0));
      this.animator.rotate(this.right_leg, 0.0F, 0.0F, (float)Math.toRadians(-2.5));
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(47.5));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(-45.0));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(42.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-42.5));
      this.animator.rotate(this.right_leg4, 0.0F, 0.0F, (float)Math.toRadians(-20.0));
      this.animator.rotate(this.left_leg4, (float)Math.toRadians(-30.0), (float)Math.toRadians(27.5), (float)Math.toRadians(45.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, (float)Math.toRadians(7.5), (float)Math.toRadians(57.5), (float)Math.toRadians(-27.5));
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, 0.0F, (float)Math.toRadians(5.0), 0.0F);
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(-37.5), (float)Math.toRadians(-47.5), (float)Math.toRadians(-67.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(10.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(15);
      this.animator.rotate(this.root, (float)Math.toRadians(-150.0), 0.0F, 0.0F);
      this.animator.move(this.root, 0.0F, -25.0F, -9.0F);
      this.animator.rotate(this.left_eye, 0.0F, 0.0F, (float)Math.toRadians(55.0));
      this.animator.rotate(this.right_eye, 0.0F, 0.0F, (float)Math.toRadians(-62.5));
      this.animator.rotate(this.left_leg, (float)Math.toRadians(-25.0), (float)Math.toRadians(-30.0), (float)Math.toRadians(-30.0));
      this.animator.rotate(this.left_joint, 0.0F, 0.0F, (float)Math.toRadians(-60.0));
      this.animator.rotate(this.right_leg, (float)Math.toRadians(-25.0), (float)Math.toRadians(17.5), (float)Math.toRadians(35.0));
      this.animator.rotate(this.right_joint, 0.0F, 0.0F, (float)Math.toRadians(77.5));
      this.animator.rotate(this.left_leg2, (float)Math.toRadians(-12.5), 0.0F, (float)Math.toRadians(-12.5));
      this.animator.rotate(this.left_joint2, 0.0F, 0.0F, (float)Math.toRadians(-65.0));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(27.5));
      this.animator.rotate(this.right_joint2, 0.0F, 0.0F, (float)Math.toRadians(27.5));
      this.animator.rotate(this.left_leg3, (float)Math.toRadians(-22.5), (float)Math.toRadians(-10.0), (float)Math.toRadians(7.5));
      this.animator.rotate(this.left_joint3, 0.0F, 0.0F, (float)Math.toRadians(-50.0));
      this.animator.rotate(this.right_leg3, 0.0F, (float)Math.toRadians(10.0), (float)Math.toRadians(-10.0));
      this.animator.rotate(this.right_joint3, 0.0F, 0.0F, (float)Math.toRadians(40.0));
      this.animator.rotate(this.right_leg4, (float)Math.toRadians(2.5), (float)Math.toRadians(10.0), (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg4, (float)Math.toRadians(2.5), (float)Math.toRadians(-17.5), (float)Math.toRadians(-2.5));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(-80.0), (float)Math.toRadians(2.5), (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_Tong, (float)Math.toRadians(17.5), (float)Math.toRadians(112.5), (float)Math.toRadians(-55.0));
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(2.5), (float)Math.toRadians(-32.5), (float)Math.toRadians(-72.5));
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(-30.0), (float)Math.toRadians(-47.5), (float)Math.toRadians(-67.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(7.5), (float)Math.toRadians(12.5), (float)Math.toRadians(-15.0));
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(80);
      this.animator.setAnimation(Amethyst_Crab_Entity.CRAB_BURROW);
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.move(this.root, -2.0F, 4.0F, 0.0F);
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-2.5));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(12.5), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(10.0), 0.0F, (float)Math.toRadians(-12.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(10.0), 0.0F, 0.0F);
      this.animator.move(this.root, 1.5F, 7.5F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-5.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(12.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(22.5), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(20.0), 0.0F, (float)Math.toRadians(-25.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(15.0), 0.0F, 0.0F);
      this.animator.move(this.root, -2.0F, 9.0F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(35.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(30.0), (float)Math.toRadians(2.5), (float)Math.toRadians(-37.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(20.0), 0.0F, 0.0F);
      this.animator.move(this.root, 1.5F, 12.5F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(35.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(30.0), (float)Math.toRadians(2.5), (float)Math.toRadians(-37.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(25.0), 0.0F, 0.0F);
      this.animator.move(this.root, -2.0F, 17.5F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(7.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(35.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(30.0), (float)Math.toRadians(2.5), (float)Math.toRadians(-35.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.move(this.root, 0.0F, 23.0F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(7.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(7.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-12.5));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(32.5), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(27.5), (float)Math.toRadians(2.5), (float)Math.toRadians(-35.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(3);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.move(this.root, 0.0F, 23.0F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(27.5));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(12.5), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(10.0), 0.0F, (float)Math.toRadians(-12.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(30);
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.move(this.root, 0.0F, 23.0F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(7.5), 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), (float)Math.toRadians(2.5), (float)Math.toRadians(1.25));
      this.animator.move(this.root, 0.0F, 23.0F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(7.5), 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), (float)Math.toRadians(-2.5), (float)Math.toRadians(-1.25));
      this.animator.move(this.root, 0.0F, 22.5F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(7.5), 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), (float)Math.toRadians(2.5), (float)Math.toRadians(1.25));
      this.animator.move(this.root, 0.0F, 22.0F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(7.5), 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), (float)Math.toRadians(-2.5), (float)Math.toRadians(-1.25));
      this.animator.move(this.root, 0.0F, 21.5F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(7.5), 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), (float)Math.toRadians(2.5), (float)Math.toRadians(1.25));
      this.animator.move(this.root, 0.0F, 21.0F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(7.5), 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), (float)Math.toRadians(-2.5), (float)Math.toRadians(-1.25));
      this.animator.move(this.root, 0.0F, 20.5F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(7.5), 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), (float)Math.toRadians(2.5), (float)Math.toRadians(1.25));
      this.animator.move(this.root, 0.0F, 20.0F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(7.5), 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), (float)Math.toRadians(-2.5), (float)Math.toRadians(-1.25));
      this.animator.move(this.root, 0.0F, 19.5F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(7.5), 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), (float)Math.toRadians(2.5), (float)Math.toRadians(1.25));
      this.animator.move(this.root, 0.0F, 19.0F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(7.5), 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), (float)Math.toRadians(-2.5), (float)Math.toRadians(-1.25));
      this.animator.move(this.root, 0.0F, 18.5F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(7.5), 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), (float)Math.toRadians(2.5), (float)Math.toRadians(1.25));
      this.animator.move(this.root, 0.0F, 18.0F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(7.5), 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(1);
      this.animator.rotate(this.root, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.move(this.root, 0.0F, 17.5F, 0.0F);
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(30.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(7.5), 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(3);
      this.animator.rotate(this.root, (float)Math.toRadians(5.0), 0.0F, (float)Math.toRadians(1.5));
      this.animator.move(this.root, 0.0F, -30.0F, 0.0F);
      this.animator.rotate(this.left_leg, 0.0F, 0.0F, (float)Math.toRadians(32.5));
      this.animator.rotate(this.left_joint, 0.0F, 0.0F, (float)Math.toRadians(-40.0));
      this.animator.rotate(this.right_leg, 0.0F, 0.0F, (float)Math.toRadians(35.0));
      this.animator.rotate(this.left_leg2, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_leg2, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.rotate(this.left_leg3, 0.0F, 0.0F, (float)Math.toRadians(-20.0));
      this.animator.rotate(this.right_leg3, 0.0F, 0.0F, (float)Math.toRadians(-42.5));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(-47.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_Tong, 0.0F, (float)Math.toRadians(32.5), 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(55.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(37.5), 0.0F, 0.0F);
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.resetKeyframe(10);
      this.animator.setAnimation(Amethyst_Crab_Entity.CRAB_BITE);
      this.animator.startKeyframe(12);
      this.animator.rotate(this.root, (float)Math.toRadians(7.5), (float)Math.toRadians(-25.0), 0.0F);
      this.animator.rotate(this.body, (float)Math.toRadians(15.0), 0.0F, (float)Math.toRadians(7.5));
      this.animator.rotate(this.left_eye, 0.0F, 0.0F, (float)Math.toRadians(-10.0));
      this.animator.rotate(this.right_eye, 0.0F, 0.0F, (float)Math.toRadians(-15.0));
      this.animator.rotate(this.left_leg, (float)Math.toRadians(12.5), (float)Math.toRadians(-27.5), (float)Math.toRadians(2.5));
      this.animator.rotate(this.left_joint, 0.0F, 0.0F, (float)Math.toRadians(-25.0));
      this.animator.rotate(this.right_leg, (float)Math.toRadians(-17.5), (float)Math.toRadians(5.0), (float)Math.toRadians(27.5));
      this.animator.rotate(this.right_joint, 0.0F, 0.0F, (float)Math.toRadians(17.5));
      this.animator.rotate(this.left_leg2, (float)Math.toRadians(7.5), (float)Math.toRadians(-12.5), (float)Math.toRadians(-15.0));
      this.animator.rotate(this.left_joint2, 0.0F, 0.0F, (float)Math.toRadians(-2.5));
      this.animator.rotate(this.right_leg2, (float)Math.toRadians(-2.5), (float)Math.toRadians(-7.5), (float)Math.toRadians(-12.5));
      this.animator.rotate(this.right_joint2, 0.0F, 0.0F, (float)Math.toRadians(22.5));
      this.animator.rotate(this.left_leg3, (float)Math.toRadians(20.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(-27.5));
      this.animator.rotate(this.right_leg3, (float)Math.toRadians(-2.5), (float)Math.toRadians(-15.0), (float)Math.toRadians(-7.5));
      this.animator.rotate(this.right_joint3, 0.0F, 0.0F, (float)Math.toRadians(-17.5));
      this.animator.rotate(this.left_leg4, (float)Math.toRadians(-22.5), (float)Math.toRadians(-17.5), (float)Math.toRadians(25.0));
      this.animator.rotate(this.right_leg4, (float)Math.toRadians(-10.0), (float)Math.toRadians(10.0), (float)Math.toRadians(-12.5));
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(7.5), (float)Math.toRadians(-52.5), (float)Math.toRadians(-27.5));
      this.animator.rotate(this.right_Tong, (float)Math.toRadians(-2.5), (float)Math.toRadians(2.5), (float)Math.toRadians(5.0));
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(45.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-17.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, (float)Math.toRadians(-52.5), (float)Math.toRadians(-40.0), (float)Math.toRadians(27.5));
      this.animator.rotate(this.left_Tong, 0.0F, (float)Math.toRadians(12.5), 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_body, 0.0F, (float)Math.toRadians(-5.0), 0.0F);
      this.animator.rotate(this.right_body, 0.0F, (float)Math.toRadians(-7.5), 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(3);
      this.animator.startKeyframe(3);
      this.animator.rotate(this.root, (float)Math.toRadians(5.0), (float)Math.toRadians(32.5), (float)Math.toRadians(-5.0));
      this.animator.rotate(this.body, 0.0F, (float)Math.toRadians(5.0), (float)Math.toRadians(2.5));
      this.animator.rotate(this.left_eye, 0.0F, (float)Math.toRadians(5.0), (float)Math.toRadians(17.5));
      this.animator.rotate(this.right_eye, 0.0F, 0.0F, (float)Math.toRadians(12.5));
      this.animator.rotate(this.left_leg, (float)Math.toRadians(-17.5), (float)Math.toRadians(20.0), (float)Math.toRadians(-37.5));
      this.animator.rotate(this.left_joint, 0.0F, 0.0F, (float)Math.toRadians(-20.0));
      this.animator.rotate(this.right_leg, (float)Math.toRadians(-2.5), (float)Math.toRadians(-17.5), (float)Math.toRadians(7.5));
      this.animator.rotate(this.right_joint, 0.0F, 0.0F, (float)Math.toRadians(32.5));
      this.animator.rotate(this.left_leg2, (float)Math.toRadians(2.5), (float)Math.toRadians(17.5), (float)Math.toRadians(2.5));
      this.animator.rotate(this.left_joint2, 0.0F, 0.0F, (float)Math.toRadians(7.5));
      this.animator.rotate(this.right_leg2, (float)Math.toRadians(-2.5), (float)Math.toRadians(-20.0), (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_joint2, 0.0F, 0.0F, (float)Math.toRadians(7.5));
      this.animator.rotate(this.left_leg3, (float)Math.toRadians(2.5), (float)Math.toRadians(7.5), (float)Math.toRadians(-15.0));
      this.animator.rotate(this.left_joint3, 0.0F, 0.0F, (float)Math.toRadians(35.0));
      this.animator.rotate(this.right_leg3, (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0), (float)Math.toRadians(7.5));
      this.animator.rotate(this.right_joint3, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_leg4, (float)Math.toRadians(-36.5), (float)Math.toRadians(-17.5), (float)Math.toRadians(37.5));
      this.animator.rotate(this.right_leg4, 0.0F, (float)Math.toRadians(7.5), 0.0F);
      this.animator.rotate(this.right_tong_leg, (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0), (float)Math.toRadians(-2.5));
      this.animator.rotate(this.right_Tong, (float)Math.toRadians(-2.5), (float)Math.toRadians(35.0), (float)Math.toRadians(7.5));
      this.animator.rotate(this.upper_claw2, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw2, (float)Math.toRadians(-27.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_tong_leg, 0.0F, (float)Math.toRadians(50.0), (float)Math.toRadians(22.5));
      this.animator.rotate(this.left_Tong, (float)Math.toRadians(50.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(72.5));
      this.animator.rotate(this.upper_claw, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.rotate(this.under_claw, (float)Math.toRadians(-35.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_body, 0.0F, (float)Math.toRadians(5.0), 0.0F);
      this.animator.rotate(this.right_body, 0.0F, (float)Math.toRadians(2.5), 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(15);
      this.animator.resetKeyframe(15);
   }

   public void setupAnim(Amethyst_Crab_Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
      this.animate(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch);
      float globalSpeed = 0.35F;
      float Speed = 0.1F;
      float globalDegree = 0.5F;
      float Degree = 0.1F;
      this.bob(this.body, globalSpeed * 0.2F, globalDegree, false, ageInTicks, 1.0F);
      this.bob(this.body, globalSpeed, globalDegree * 1.6F, false, limbSwing, limbSwingAmount);
      this.flap(this.body, globalSpeed, globalDegree * 0.2F, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
      this.swing(this.right_tong_leg, Speed * 3.0F, Degree, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
      this.swing(this.left_tong_leg, Speed * 3.0F, Degree, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
      this.swing(this.right_Tong, Speed * 3.0F, globalDegree, true, 0.0F, 0.5F, limbSwing, limbSwingAmount);
      this.swing(this.left_Tong, Speed * 3.0F, Degree * 0.5F, false, 0.0F, 0.05F, limbSwing, limbSwingAmount);
      this.walk(this.upper_claw, globalSpeed * 0.1F, Degree * 2.0F, false, 0.0F, 0.1F, ageInTicks, 1.0F);
      this.walk(this.under_claw, globalSpeed * 0.1F, Degree * 2.0F, true, 0.0F, 0.1F, ageInTicks, 1.0F);
      this.walk(this.upper_claw2, globalSpeed * 0.1F, Degree * 2.0F, false, 0.0F, 0.1F, ageInTicks, 1.0F);
      this.walk(this.under_claw2, globalSpeed * 0.1F, Degree * 2.0F, true, 0.0F, 0.1F, ageInTicks, 1.0F);
      this.flap(this.left_eye, Speed, globalDegree * 0.4F, false, 0.0F, -0.1F, ageInTicks, 1.0F);
      this.flap(this.right_eye, Speed, globalDegree * 0.4F, true, 0.0F, -0.1F, ageInTicks, 1.0F);
      this.swing(this.left_leg, globalSpeed, globalDegree * 1.6F, false, 0.0F, 0.1F, limbSwing, limbSwingAmount);
      this.flap(this.left_leg, globalSpeed, globalDegree * 0.6F, false, 0.0F, -0.25F, limbSwing, limbSwingAmount);
      this.swing(this.left_leg2, globalSpeed, globalDegree * 1.6F, false, 1.57F, 0.1F, limbSwing, limbSwingAmount);
      this.flap(this.left_leg2, globalSpeed, globalDegree * 0.6F, false, 1.57F, -0.25F, limbSwing, limbSwingAmount);
      this.swing(this.left_leg3, globalSpeed, globalDegree * 1.6F, false, 3.14F, 0.1F, limbSwing, limbSwingAmount);
      this.flap(this.left_leg3, globalSpeed, globalDegree * 0.6F, false, 3.14F, -0.25F, limbSwing, limbSwingAmount);
      this.swing(this.left_leg4, globalSpeed, globalDegree * 1.6F, false, 4.71F, 0.1F, limbSwing, limbSwingAmount);
      this.swing(this.right_leg, globalSpeed, globalDegree * 1.6F, false, 0.0F, -0.1F, limbSwing, limbSwingAmount);
      this.flap(this.right_leg, globalSpeed, globalDegree * 0.6F, false, 0.0F, 0.25F, limbSwing, limbSwingAmount);
      this.swing(this.right_leg2, globalSpeed, globalDegree * 1.6F, false, 1.57F, -0.1F, limbSwing, limbSwingAmount);
      this.flap(this.right_leg2, globalSpeed, globalDegree * 0.6F, false, 1.57F, 0.25F, limbSwing, limbSwingAmount);
      this.swing(this.right_leg3, globalSpeed, globalDegree * 1.6F, false, 3.14F, -0.1F, limbSwing, limbSwingAmount);
      this.flap(this.right_leg3, globalSpeed, globalDegree * 0.6F, false, 3.14F, 0.25F, limbSwing, limbSwingAmount);
      this.swing(this.right_leg4, globalSpeed, globalDegree * 1.6F, false, 4.71F, -0.1F, limbSwing, limbSwingAmount);
   }

   public void setRotationAngle(AdvancedModelBox AdvancedModelBox, float x, float y, float z) {
      AdvancedModelBox.rotateAngleX = x;
      AdvancedModelBox.rotateAngleY = y;
      AdvancedModelBox.rotateAngleZ = z;
   }
}
