package com.github.L_Ender.cataclysm.client.model.entity;

import com.github.L_Ender.cataclysm.entity.AnimationMonster.BossMonsters.Ender_Guardian_Entity;
import com.github.L_Ender.lionfishapi.client.model.Animations.ModelAnimator;
import com.github.L_Ender.lionfishapi.client.model.tools.AdvancedEntityModel;
import com.github.L_Ender.lionfishapi.client.model.tools.AdvancedModelBox;
import com.github.L_Ender.lionfishapi.client.model.tools.BasicModelPart;
import com.github.L_Ender.lionfishapi.server.animation.IAnimatedEntity;
import com.google.common.collect.ImmutableList;

public class Ender_Guardian_Model extends AdvancedEntityModel<Ender_Guardian_Entity> {
   public final AdvancedModelBox root;
   public final AdvancedModelBox lowerbody;
   public final AdvancedModelBox upperbody;
   public final AdvancedModelBox right_arm;
   public final AdvancedModelBox rightarmor;
   public final AdvancedModelBox rightarmorspike;
   public final AdvancedModelBox right_arm2;
   public final AdvancedModelBox right_fist;
   public final AdvancedModelBox left_arm;
   public final AdvancedModelBox leftarmor;
   public final AdvancedModelBox leftarmorspike;
   public final AdvancedModelBox left_arm2;
   public final AdvancedModelBox left_fist;
   public final AdvancedModelBox helmet;
   public final AdvancedModelBox head;
   public final AdvancedModelBox upperhelmet;
   public final AdvancedModelBox armor;
   public final AdvancedModelBox voidstone;
   public final AdvancedModelBox right_leg;
   public final AdvancedModelBox left_leg;
   private ModelAnimator animator;

   public Ender_Guardian_Model() {
      this.texWidth = 256;
      this.texHeight = 256;
      this.root = new AdvancedModelBox(this);
      this.root.setRotationPoint(0.0F, 24.0F, 0.0F);
      this.lowerbody = new AdvancedModelBox(this);
      this.lowerbody.setRotationPoint(0.0F, -22.0F, 0.0F);
      this.root.addChild(this.lowerbody);
      this.lowerbody.setTextureOffset(121, 0).addBox(-11.0F, -8.0F, -7.0F, 22.0F, 8.0F, 14.0F, 0.0F, false);
      this.upperbody = new AdvancedModelBox(this);
      this.upperbody.setRotationPoint(0.0F, -7.0F, 0.0F);
      this.lowerbody.addChild(this.upperbody);
      this.upperbody.setTextureOffset(0, 0).addBox(-20.0F, -32.0F, -10.0F, 40.0F, 32.0F, 20.0F, 0.0F, false);
      this.right_arm = new AdvancedModelBox(this);
      this.right_arm.setRotationPoint(-20.0F, -25.0F, 0.0F);
      this.upperbody.addChild(this.right_arm);
      this.right_arm.setTextureOffset(94, 150).addBox(-14.0F, -6.0F, -6.0F, 14.0F, 20.0F, 12.0F, 0.0F, false);
      this.rightarmor = new AdvancedModelBox(this);
      this.rightarmor.setRotationPoint(-7.0F, 0.0F, -10.0F);
      this.right_arm.addChild(this.rightarmor);
      this.rightarmor.setTextureOffset(103, 35).addBox(-10.0F, -7.0F, 1.0F, 12.0F, 18.0F, 18.0F, 0.0F, false);
      this.rightarmorspike = new AdvancedModelBox(this);
      this.rightarmorspike.setRotationPoint(-7.0F, -3.0F, 10.0F);
      this.rightarmor.addChild(this.rightarmorspike);
      this.setRotationAngle(this.rightarmorspike, 0.0F, 0.0F, -0.6109F);
      this.rightarmorspike.setTextureOffset(0, 162).addBox(-3.0F, -12.0F, -3.0F, 6.0F, 12.0F, 6.0F, 0.0F, false);
      this.right_arm2 = new AdvancedModelBox(this);
      this.right_arm2.setRotationPoint(-8.5F, 14.0F, 0.0F);
      this.right_arm.addChild(this.right_arm2);
      this.right_arm2.setTextureOffset(146, 23).addBox(-5.5F, 0.0F, -6.0F, 10.0F, 14.0F, 12.0F, 0.0F, false);
      this.right_fist = new AdvancedModelBox(this);
      this.right_fist.setRotationPoint(-5.5F, 14.0F, 0.0F);
      this.right_arm2.addChild(this.right_fist);
      this.right_fist.setTextureOffset(142, 72).addBox(0.0F, -1.0F, -6.0F, 12.0F, 12.0F, 12.0F, 0.25F, false);
      this.left_arm = new AdvancedModelBox(this);
      this.left_arm.setRotationPoint(20.0F, -25.0F, 0.0F);
      this.upperbody.addChild(this.left_arm);
      this.left_arm.setTextureOffset(94, 150).addBox(0.0F, -6.0F, -6.0F, 14.0F, 20.0F, 12.0F, 0.0F, true);
      this.leftarmor = new AdvancedModelBox(this);
      this.leftarmor.setRotationPoint(7.0F, 0.0F, -10.0F);
      this.left_arm.addChild(this.leftarmor);
      this.leftarmor.setTextureOffset(103, 35).addBox(-2.0F, -7.0F, 1.0F, 12.0F, 18.0F, 18.0F, 0.0F, true);
      this.leftarmorspike = new AdvancedModelBox(this);
      this.leftarmorspike.setRotationPoint(7.0F, -3.0F, 10.0F);
      this.leftarmor.addChild(this.leftarmorspike);
      this.setRotationAngle(this.leftarmorspike, 0.0F, 0.0F, 0.6109F);
      this.leftarmorspike.setTextureOffset(0, 162).addBox(-3.0F, -12.0F, -3.0F, 6.0F, 12.0F, 6.0F, 0.0F, true);
      this.left_arm2 = new AdvancedModelBox(this);
      this.left_arm2.setRotationPoint(8.5F, 14.0F, 0.0F);
      this.left_arm.addChild(this.left_arm2);
      this.left_arm2.setTextureOffset(146, 23).addBox(-4.5F, 0.0F, -6.0F, 10.0F, 14.0F, 12.0F, 0.0F, true);
      this.left_fist = new AdvancedModelBox(this);
      this.left_fist.setRotationPoint(5.5F, 14.0F, 0.0F);
      this.left_arm2.addChild(this.left_fist);
      this.left_fist.setTextureOffset(142, 72).addBox(-12.0F, -1.0F, -6.0F, 12.0F, 12.0F, 12.0F, 0.25F, true);
      this.helmet = new AdvancedModelBox(this);
      this.helmet.setRotationPoint(0.0F, -28.0F, -7.0F);
      this.upperbody.addChild(this.helmet);
      this.helmet.setTextureOffset(0, 139).addBox(-8.0F, 2.0F, -16.0F, 16.0F, 6.0F, 16.0F, 0.0F, false);
      this.helmet.setTextureOffset(58, 155).addBox(-10.0F, -1.0F, -12.0F, 6.0F, 10.0F, 7.0F, 0.0F, false);
      this.helmet.setTextureOffset(161, 114).addBox(4.0F, -1.0F, -12.0F, 6.0F, 10.0F, 7.0F, 0.0F, false);
      this.head = new AdvancedModelBox(this);
      this.head.setRotationPoint(0.0F, -4.0F, -8.0F);
      this.helmet.addChild(this.head);
      this.head.setTextureOffset(49, 99).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 6.0F, 6.0F, 0.0F, false);
      this.upperhelmet = new AdvancedModelBox(this);
      this.upperhelmet.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.helmet.addChild(this.upperhelmet);
      this.upperhelmet.setTextureOffset(106, 121).addBox(-8.0F, -7.75F, -16.0F, 16.0F, 12.0F, 16.0F, -0.25F, false);
      this.upperhelmet.setTextureOffset(147, 150).addBox(-3.0F, -9.5F, -16.7F, 6.0F, 13.0F, 10.0F, 0.0F, false);
      this.armor = new AdvancedModelBox(this);
      this.armor.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.upperbody.addChild(this.armor);
      this.armor.setTextureOffset(0, 53).addBox(-17.0F, -34.0F, -12.0F, 34.0F, 21.0F, 24.0F, 0.0F, false);
      this.armor.setTextureOffset(91, 73).addBox(-25.0F, -35.0F, -13.0F, 12.0F, 21.0F, 26.0F, 0.0F, false);
      this.armor.setTextureOffset(91, 73).addBox(13.0F, -35.0F, -13.0F, 12.0F, 21.0F, 26.0F, 0.0F, true);
      this.voidstone = new AdvancedModelBox(this);
      this.voidstone.setRotationPoint(0.0F, -16.0F, 10.0F);
      this.upperbody.addChild(this.voidstone);
      this.setRotationAngle(this.voidstone, -0.7854F, 0.0F, 0.0F);
      this.voidstone.setTextureOffset(0, 99).addBox(-8.0F, -8.0F, -8.0F, 16.0F, 16.0F, 16.0F, 1.0F, false);
      this.right_leg = new AdvancedModelBox(this);
      this.right_leg.setRotationPoint(-11.0F, -22.0F, 0.0F);
      this.root.addChild(this.right_leg);
      this.right_leg.setTextureOffset(49, 116).addBox(-8.0F, 0.0F, -8.0F, 12.0F, 22.0F, 16.0F, 0.0F, false);
      this.left_leg = new AdvancedModelBox(this);
      this.left_leg.setRotationPoint(11.0F, -22.0F, 0.0F);
      this.root.addChild(this.left_leg);
      this.left_leg.setTextureOffset(49, 116).addBox(-4.0F, 0.0F, -8.0F, 12.0F, 22.0F, 16.0F, 0.0F, true);
      this.animator = ModelAnimator.create();
      this.updateDefaultPose();
   }

   public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4) {
      this.resetToDefaultPose();
      this.animator.update(entity);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_RIGHT_ATTACK);
      this.animator.startKeyframe(10);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(5.0), (float)Math.toRadians(32.5), (float)Math.toRadians(2.5));
      this.animator.move(this.upperbody, 0.0F, 0.0F, -1.0F);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-5.0), 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -2.0F);
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(17.5), 0.0F);
      this.animator.move(this.right_leg, 1.0F, 0.0F, 5.0F);
      this.animator.rotate(this.armor, 0.0F, 0.0F, (float)Math.toRadians(7.5));
      this.animator.move(this.armor, -3.0F, 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-17.5), 0.0F, (float)Math.toRadians(35.0));
      this.animator.move(this.right_arm, 2.0F, 1.0F, 1.0F);
      this.animator.rotate(this.rightarmor, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-80.0), (float)Math.toRadians(-55.0), (float)Math.toRadians(15.0));
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(-25.0), (float)Math.toRadians(-2.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(7.5), (float)Math.toRadians(2.5));
      this.animator.move(this.left_arm, 1.0F, 3.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-37.5), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, -2.0F, 1.0F, 2.0F);
      this.animator.move(this.left_fist, 0.0F, -5.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(3);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(10.0), (float)Math.toRadians(-7.5), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(35.0), (float)Math.toRadians(-30.0), (float)Math.toRadians(-10.0));
      this.animator.move(this.upperbody, 0.0F, 0.0F, -1.0F);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-12.5), 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, 2.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, -4.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
      this.animator.move(this.right_arm, -1.0F, 2.0F, -7.0F);
      this.animator.rotate(this.rightarmor, (float)Math.toRadians(10.0), 0.0F, 0.0F);
      this.animator.move(this.rightarmor, 0.0F, -7.0F, -2.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), (float)Math.toRadians(-87.5), (float)Math.toRadians(32.5));
      this.animator.move(this.right_arm2, 2.0F, 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm, 0.0F, -2.0F, -1.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, -2.0F, 2.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(2.5));
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(7);
      this.animator.resetKeyframe(10);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_LEFT_ATTACK);
      this.animator.startKeyframe(8);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(5.0), (float)Math.toRadians(-32.5), (float)Math.toRadians(-2.5));
      this.animator.move(this.upperbody, 0.0F, 0.0F, -1.0F);
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(5.0), 0.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, -2.0F);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-17.5), 0.0F);
      this.animator.move(this.left_leg, -1.0F, 0.0F, 5.0F);
      this.animator.rotate(this.armor, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.move(this.armor, 3.0F, 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-17.5), 0.0F, (float)Math.toRadians(-35.0));
      this.animator.move(this.left_arm, -2.0F, 1.0F, 1.0F);
      this.animator.rotate(this.leftarmor, 0.0F, 0.0F, (float)Math.toRadians(-5.0));
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-80.0), (float)Math.toRadians(55.0), (float)Math.toRadians(-15.0));
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(25.0), (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(-2.5));
      this.animator.move(this.right_arm, -1.0F, 3.0F, 0.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-37.5), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 2.0F, 1.0F, 2.0F);
      this.animator.move(this.right_fist, 0.0F, -5.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(7);
      this.animator.startKeyframe(3);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(10.0), (float)Math.toRadians(7.5), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(35.0), (float)Math.toRadians(30.0), (float)Math.toRadians(10.0));
      this.animator.move(this.upperbody, 0.0F, 0.0F, -1.0F);
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(-12.5), 0.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 2.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -4.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
      this.animator.move(this.left_arm, 1.0F, 2.0F, -7.0F);
      this.animator.rotate(this.leftarmor, (float)Math.toRadians(10.0), 0.0F, 0.0F);
      this.animator.move(this.leftarmor, 0.0F, -7.0F, -2.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), (float)Math.toRadians(87.5), (float)Math.toRadians(-32.5));
      this.animator.move(this.left_arm2, -2.0F, 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm, 0.0F, -2.0F, -1.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, -2.0F, 2.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(-12.0), (float)Math.toRadians(-2.5));
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(12);
      this.animator.resetKeyframe(10);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_RIGHT_STRONG_ATTACK);
      this.animator.startKeyframe(15);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(5.0), (float)Math.toRadians(32.5), (float)Math.toRadians(2.5));
      this.animator.move(this.upperbody, 0.0F, 0.0F, -1.0F);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-5.0), 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -2.0F);
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(17.5), 0.0F);
      this.animator.move(this.right_leg, 1.0F, 0.0F, 5.0F);
      this.animator.rotate(this.armor, 0.0F, 0.0F, (float)Math.toRadians(7.5));
      this.animator.move(this.armor, -3.0F, 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-17.5), 0.0F, (float)Math.toRadians(35.0));
      this.animator.move(this.right_arm, 2.0F, 1.0F, 1.0F);
      this.animator.rotate(this.rightarmor, 0.0F, 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-80.0), (float)Math.toRadians(-55.0), (float)Math.toRadians(15.0));
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(-25.0), (float)Math.toRadians(-2.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(7.5), (float)Math.toRadians(2.5));
      this.animator.move(this.left_arm, 1.0F, 3.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-37.5), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, -2.0F, 1.0F, 2.0F);
      this.animator.move(this.left_fist, 0.0F, -5.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(12);
      this.animator.startKeyframe(3);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(10.0), (float)Math.toRadians(-7.5), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(27.5), (float)Math.toRadians(-30.0), (float)Math.toRadians(-10.0));
      this.animator.move(this.upperbody, 0.0F, 0.0F, -1.0F);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-12.5), 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, 2.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, -4.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-60.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
      this.animator.move(this.right_arm, -1.0F, 9.0F, 0.0F);
      this.animator.rotate(this.rightarmor, (float)Math.toRadians(10.0), 0.0F, 0.0F);
      this.animator.move(this.rightarmor, 0.0F, -7.0F, -2.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), (float)Math.toRadians(-87.5), (float)Math.toRadians(32.5));
      this.animator.move(this.right_arm2, 2.0F, 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm, 0.0F, -2.0F, -1.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, -2.0F, 2.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(2.5));
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(13);
      this.animator.resetKeyframe(17);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_LEFT_STRONG_ATTACK);
      this.animator.startKeyframe(17);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(5.0), (float)Math.toRadians(-32.5), (float)Math.toRadians(-2.5));
      this.animator.move(this.upperbody, 0.0F, 0.0F, -1.0F);
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(5.0), 0.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, -2.0F);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-17.5), 0.0F);
      this.animator.move(this.left_leg, -1.0F, 0.0F, 5.0F);
      this.animator.rotate(this.armor, 0.0F, 0.0F, (float)Math.toRadians(-7.5));
      this.animator.move(this.armor, 3.0F, 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-17.5), 0.0F, (float)Math.toRadians(-35.0));
      this.animator.move(this.left_arm, -2.0F, 1.0F, 1.0F);
      this.animator.rotate(this.leftarmor, 0.0F, 0.0F, (float)Math.toRadians(-5.0));
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-80.0), (float)Math.toRadians(55.0), (float)Math.toRadians(-15.0));
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(25.0), (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(-2.5));
      this.animator.move(this.right_arm, -1.0F, 3.0F, 0.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-37.5), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 2.0F, 1.0F, 2.0F);
      this.animator.move(this.right_fist, 0.0F, -5.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(15);
      this.animator.startKeyframe(3);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(10.0), (float)Math.toRadians(7.5), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(27.5), (float)Math.toRadians(30.0), (float)Math.toRadians(10.0));
      this.animator.move(this.upperbody, 0.0F, 0.0F, -1.0F);
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(-12.5), 0.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 2.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -4.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-60.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
      this.animator.move(this.left_arm, 1.0F, 9.0F, 0.0F);
      this.animator.rotate(this.leftarmor, (float)Math.toRadians(10.0), 0.0F, 0.0F);
      this.animator.move(this.leftarmor, 0.0F, -7.0F, -2.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), (float)Math.toRadians(87.5), (float)Math.toRadians(-32.5));
      this.animator.move(this.left_arm2, -2.0F, 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm, 0.0F, -2.0F, -1.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, -2.0F, 2.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(-12.0), (float)Math.toRadians(-2.5));
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_BURST_ATTACK);
      this.animator.startKeyframe(15);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -3.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 4.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.move(this.lowerbody, 0.0F, 0.0F, 2.0F);
      this.animator.rotate(this.armor, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(35.0), (float)Math.toRadians(-5.5), (float)Math.toRadians(-45.0));
      this.animator.rotate(this.right_arm, (float)Math.toRadians(35.0), (float)Math.toRadians(5.5), (float)Math.toRadians(45.0));
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.move(this.right_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(3);
      this.animator.rotate(this.left_leg, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_leg, (float)Math.toRadians(-5.0), 0.0F, 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, 7.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, -5.0F);
      this.animator.move(this.lowerbody, 0.0F, 3.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(12.5), 0.0F, 0.0F);
      this.animator.rotate(this.armor, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-80.0), (float)Math.toRadians(12.5), (float)Math.toRadians(-45.0));
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-80.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(45.0));
      this.animator.move(this.left_arm, 0.0F, 0.0F, -10.0F);
      this.animator.move(this.right_arm, 0.0F, 0.0F, -10.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_UPPERCUT_AND_BULLET);
      this.animator.startKeyframe(15);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(12.5), 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, 4.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, -3.0F);
      this.animator.rotate(this.lowerbody, 0.0F, (float)Math.toRadians(-15.0), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-2.5), (float)Math.toRadians(-20.0), (float)Math.toRadians(5.0));
      this.animator.rotate(this.armor, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_arm, (float)Math.toRadians(17.5), (float)Math.toRadians(-5.0), (float)Math.toRadians(10.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-77.5), 0.0F, 0.0F);
      this.animator.move(this.right_arm, 0.0F, -1.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(20.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(-15.0));
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.lowerbody, 0.0F, (float)Math.toRadians(20.0), 0.0F);
      this.animator.rotate(this.upperbody, 0.0F, (float)Math.toRadians(35.0), 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(35.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-77.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-50.0), (float)Math.toRadians(-2.5), (float)Math.toRadians(-52.5));
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(20);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.lowerbody, 0.0F, (float)Math.toRadians(-7.5), 0.0F);
      this.animator.rotate(this.upperbody, 0.0F, (float)Math.toRadians(-7.5), 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(35.0), (float)Math.toRadians(20.0), (float)Math.toRadians(15.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-77.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(45.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(-35.0));
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(20);
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_STOMP);
      this.animator.startKeyframe(15);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 1.0F);
      this.animator.move(this.left_leg, 0.0F, -9.0F, -9.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0F, 0.0F);
      this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(-5.0));
      this.animator.move(this.right_arm, -1.0F, 0.0F, 0.0F);
      this.animator.move(this.left_arm, 1.0F, 0.0F, 0.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(15);
      this.animator.startKeyframe(3);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 2.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -8.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(15.0), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0F, 0.0F);
      this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_RAGE_STOMP);
      this.animator.startKeyframe(15);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 1.0F);
      this.animator.move(this.left_leg, 0.0F, -9.0F, -9.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0F, 0.0F);
      this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(-5.0));
      this.animator.move(this.right_arm, -1.0F, 0.0F, 0.0F);
      this.animator.move(this.left_arm, 1.0F, 0.0F, 0.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(15);
      this.animator.startKeyframe(3);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 2.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -8.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(15.0), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0F, 0.0F);
      this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(5);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 1.0F);
      this.animator.move(this.left_leg, 0.0F, -9.0F, -9.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0F, 0.0F);
      this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(-5.0));
      this.animator.move(this.right_arm, -1.0F, 0.0F, 0.0F);
      this.animator.move(this.left_arm, 1.0F, 0.0F, 0.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(3);
      this.animator.startKeyframe(3);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 2.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -8.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(15.0), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0F, 0.0F);
      this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(3);
      this.animator.startKeyframe(3);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 1.0F);
      this.animator.move(this.left_leg, 0.0F, -9.0F, -9.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0F, 0.0F);
      this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(-5.0));
      this.animator.move(this.right_arm, -1.0F, 0.0F, 0.0F);
      this.animator.move(this.left_arm, 1.0F, 0.0F, 0.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(3);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 2.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -8.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(15.0), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), 0.0F, 0.0F);
      this.animator.rotate(this.armor, (float)Math.toRadians(2.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(5.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_MASS_DESTRUCTION);
      this.animator.startKeyframe(25);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-22.5), 0.0F, 0.0F);
      this.animator.rotate(this.armor, (float)Math.toRadians(-2.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-97.5), (float)Math.toRadians(25.0), (float)Math.toRadians(25.0));
      this.animator.move(this.right_arm, 0.0F, 0.0F, -4.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-97.5), (float)Math.toRadians(-25.0), (float)Math.toRadians(-25.0));
      this.animator.move(this.left_arm, 0.0F, 0.0F, -4.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(47.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-57.5), (float)Math.toRadians(25.0), (float)Math.toRadians(25.0));
      this.animator.move(this.right_arm, 0.0F, 0.0F, -8.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-57.5), (float)Math.toRadians(-25.0), (float)Math.toRadians(-25.0));
      this.animator.move(this.left_arm, 0.0F, 0.0F, -8.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.resetKeyframe(25);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_FALLEN);
      this.animator.startKeyframe(15);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-20.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(30.0), (float)Math.toRadians(10.0), (float)Math.toRadians(72.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(30.0), (float)Math.toRadians(-10.0), (float)Math.toRadians(-75.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(12.5), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-82.5), (float)Math.toRadians(10.0), (float)Math.toRadians(72.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-82.5), (float)Math.toRadians(-10.0), (float)Math.toRadians(-75.0));
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(20);
      this.animator.startKeyframe(6);
      this.animator.move(this.root, 0.0F, 14.0F, 0.0F);
      this.animator.rotate(this.right_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(90.0), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-52.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-65.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-65.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-42.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-42.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(15);
      this.animator.move(this.root, 0.0F, 14.0F, 0.0F);
      this.animator.rotate(this.right_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(90.0), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-57.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-35.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-35.0), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(-42.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(5);
      this.animator.move(this.root, 0.0F, 14.0F, 0.0F);
      this.animator.rotate(this.right_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(90.0), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-35.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-92.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-92.5), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-35.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-35.0), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(20.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(100);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_RAGE_UPPERCUT);
      this.animator.startKeyframe(15);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(12.5), 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, 4.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, -3.0F);
      this.animator.rotate(this.lowerbody, 0.0F, (float)Math.toRadians(-15.0), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-2.5), (float)Math.toRadians(-20.0), (float)Math.toRadians(5.0));
      this.animator.rotate(this.armor, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_arm, (float)Math.toRadians(17.5), (float)Math.toRadians(-5.0), (float)Math.toRadians(10.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-77.5), 0.0F, 0.0F);
      this.animator.move(this.right_arm, 0.0F, -1.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(20.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(-15.0));
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.lowerbody, 0.0F, (float)Math.toRadians(20.0), 0.0F);
      this.animator.rotate(this.upperbody, 0.0F, (float)Math.toRadians(35.0), 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(35.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-77.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-50.0), (float)Math.toRadians(-2.5), (float)Math.toRadians(-52.5));
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(20);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.lowerbody, 0.0F, (float)Math.toRadians(-7.5), 0.0F);
      this.animator.rotate(this.upperbody, 0.0F, (float)Math.toRadians(-7.5), 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(35.0), (float)Math.toRadians(20.0), (float)Math.toRadians(15.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-77.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(45.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(-35.0));
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(3);
      this.animator.startKeyframe(10);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-17.5), 0.0F, 0.0F);
      this.animator.move(this.right_arm, 0.0F, 0.0F, -8.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-115.0), 0.0F, (float)Math.toRadians(32.5));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.move(this.left_arm, 0.0F, 0.0F, -7.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-115.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(-32.5));
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(12);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(22.5), 0.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm, 0.0F, 0.0F, -8.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-60.0), (float)Math.toRadians(5.0), (float)Math.toRadians(32.5));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.move(this.left_arm, 0.0F, 0.0F, -7.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-60.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(-32.5));
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(20);
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_HUG_ME);
      this.animator.startKeyframe(15);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(27.5), 0.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 8.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -6.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(35.0), (float)Math.toRadians(-15.0), 0.0F);
      this.animator.move(this.upperbody, 0.0F, 2.0F, 0.0F);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-35.0), 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(42.5), (float)Math.toRadians(-2.5), (float)Math.toRadians(62.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(60.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-57.5));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(-25.0), (float)Math.toRadians(-7.5), 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(20);
      this.animator.startKeyframe(6);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(-17.5), 0.0F);
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(25.0), 0.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, -6.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, 9.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-22.5), (float)Math.toRadians(2.5), 0.0F);
      this.animator.rotate(this.armor, 0.0F, 0.0F, (float)Math.toRadians(2.5));
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-60.0), (float)Math.toRadians(5.0), (float)Math.toRadians(45.0));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-62.5), (float)Math.toRadians(2.5), (float)Math.toRadians(-35.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-82.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(17.5), (float)Math.toRadians(5.0));
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(20);
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_AIR_STRIKE1);
      this.animator.startKeyframe(15);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-10.0), (float)Math.toRadians(47.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-17.5), (float)Math.toRadians(10.0), (float)Math.toRadians(-47.5));
      this.animator.move(this.right_arm, 0.0F, 0.0F, -4.0F);
      this.animator.move(this.left_arm, 0.0F, 0.0F, -4.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-110.0), (float)Math.toRadians(-30.0), 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-110.0), (float)Math.toRadians(30.0), 0.0F);
      this.animator.move(this.right_arm2, 0.0F, 6.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(3);
      this.animator.startKeyframe(2);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-50.0), (float)Math.toRadians(-25.0), (float)Math.toRadians(32.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-50.0), (float)Math.toRadians(25.0), (float)Math.toRadians(-32.5));
      this.animator.move(this.right_arm, 2.5F, 2.0F, -6.0F);
      this.animator.move(this.left_arm, -2.75F, 2.0F, -6.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-105.0), (float)Math.toRadians(-50.0), (float)Math.toRadians(12.5));
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-105.0), (float)Math.toRadians(50.0), (float)Math.toRadians(-12.5));
      this.animator.move(this.right_arm2, 0.0F, 6.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(20);
      this.animator.startKeyframe(8);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(-17.5), 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(-5.0), 0.0F, 0.0F);
      this.animator.move(this.lowerbody, 0.0F, 3.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-27.5), (float)Math.toRadians(-2.5), (float)Math.toRadians(5.0));
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-82.5), (float)Math.toRadians(17.5), (float)Math.toRadians(45.0));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-100.0), (float)Math.toRadians(-17.5), (float)Math.toRadians(-27.5));
      this.animator.move(this.right_arm, 2.0F, -2.0F, -2.0F);
      this.animator.move(this.left_arm, -2.0F, -1.0F, -3.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-82.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(17.5), (float)Math.toRadians(5.0));
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(30.0), 0.0F);
      this.animator.move(this.right_leg, 0.0F, 2.0F, -6.0F);
      this.animator.move(this.left_leg, 0.0F, 3.0F, 9.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(60);
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_AIR_STRIKE2);
      this.animator.startKeyframe(0);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(-17.5), 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(-5.0), 0.0F, 0.0F);
      this.animator.move(this.lowerbody, 0.0F, 3.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-27.5), (float)Math.toRadians(-2.5), (float)Math.toRadians(5.0));
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-82.5), (float)Math.toRadians(17.5), (float)Math.toRadians(45.0));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-100.0), (float)Math.toRadians(-17.5), (float)Math.toRadians(-27.5));
      this.animator.move(this.right_arm, 2.0F, -2.0F, -2.0F);
      this.animator.move(this.left_arm, -2.0F, -1.0F, -3.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-82.5), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(17.5), (float)Math.toRadians(17.5), (float)Math.toRadians(5.0));
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(30.0), 0.0F);
      this.animator.move(this.right_leg, 0.0F, 2.0F, -6.0F);
      this.animator.move(this.left_leg, 0.0F, 3.0F, 9.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(4);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(-17.5), 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(35.0), 0.0F, 0.0F);
      this.animator.move(this.lowerbody, 0.0F, 7.0F, 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(27.5), (float)Math.toRadians(12.5), (float)Math.toRadians(-5.0));
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(-15.0), (float)Math.toRadians(32.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(15.0), (float)Math.toRadians(-32.5));
      this.animator.move(this.right_arm, 2.0F, 9.0F, -6.0F);
      this.animator.move(this.left_arm, -1.0F, 11.0F, -6.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(20.0), 0.0F);
      this.animator.rotate(this.left_leg, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, -6.0F);
      this.animator.move(this.left_leg, 0.0F, 1.0F, 5.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(20);
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_RIGHT_SWING);
      this.animator.startKeyframe(0);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(10.0), (float)Math.toRadians(-7.5), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(35.0), (float)Math.toRadians(-30.0), (float)Math.toRadians(-10.0));
      this.animator.move(this.upperbody, 0.0F, 0.0F, -1.0F);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-12.5), 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, 2.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, -4.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(5.0));
      this.animator.move(this.right_arm, -1.0F, 2.0F, -7.0F);
      this.animator.rotate(this.rightarmor, (float)Math.toRadians(10.0), 0.0F, 0.0F);
      this.animator.move(this.rightarmor, 0.0F, -7.0F, -2.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-32.5), (float)Math.toRadians(-87.5), (float)Math.toRadians(32.5));
      this.animator.move(this.right_arm2, 2.0F, 0.0F, 0.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm, 0.0F, -2.0F, -1.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, -2.0F, 2.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(2.5));
      this.animator.endKeyframe();
      this.animator.startKeyframe(15);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(5.0), 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(2.5), (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(27.5), (float)Math.toRadians(45.0), (float)Math.toRadians(12.5));
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-10.0), (float)Math.toRadians(32.5), 0.0F);
      this.animator.move(this.right_arm, 0.0F, -2.0F, -2.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-65.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, -2.0F, -2.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-57.5));
      this.animator.move(this.left_arm, 4.0F, 8.0F, -2.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, -6.0F, -6.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(-12.5), (float)Math.toRadians(-2.5));
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(12.5), 0.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 8.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -6.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(8);
      this.animator.startKeyframe(4);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(5.0), 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(2.5), (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(2.5), (float)Math.toRadians(-45.0), (float)Math.toRadians(12.5));
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-20.0), (float)Math.toRadians(30.0), (float)Math.toRadians(25.0));
      this.animator.move(this.right_arm, 0.0F, -2.0F, -2.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-75.0), (float)Math.toRadians(-25.0), 0.0F);
      this.animator.move(this.right_arm2, 0.0F, -2.0F, 2.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(32.5), (float)Math.toRadians(7.5), (float)Math.toRadians(-57.5));
      this.animator.move(this.left_arm, 4.0F, 8.0F, 2.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(-5.0), (float)Math.toRadians(25.0), (float)Math.toRadians(-12.5));
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(12.5), 0.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 8.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -6.0F);
      this.animator.endKeyframe();
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_LEFT_SWING);
      this.animator.startKeyframe(0);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(10.0), (float)Math.toRadians(7.5), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(35.0), (float)Math.toRadians(30.0), (float)Math.toRadians(10.0));
      this.animator.move(this.upperbody, 0.0F, 0.0F, -1.0F);
      this.animator.rotate(this.right_leg, 0.0F, (float)Math.toRadians(-12.5), 0.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, 2.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -4.0F);
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(7.5), (float)Math.toRadians(-5.0));
      this.animator.move(this.left_arm, 1.0F, 2.0F, -7.0F);
      this.animator.rotate(this.leftarmor, (float)Math.toRadians(10.0), 0.0F, 0.0F);
      this.animator.move(this.leftarmor, 0.0F, -7.0F, -2.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-32.5), (float)Math.toRadians(87.5), (float)Math.toRadians(-32.5));
      this.animator.move(this.left_arm2, -2.0F, 0.0F, 0.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm, 0.0F, -2.0F, -1.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, -2.0F, 2.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(-12.0), (float)Math.toRadians(-2.5));
      this.animator.endKeyframe();
      this.animator.startKeyframe(15);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(-5.0), 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(2.5), (float)Math.toRadians(-10.0), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(27.5), (float)Math.toRadians(-45.0), (float)Math.toRadians(-12.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-10.0), (float)Math.toRadians(-32.5), 0.0F);
      this.animator.move(this.left_arm, 0.0F, -2.0F, -2.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-65.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, -2.0F, -2.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(57.5));
      this.animator.move(this.right_arm, -4.0F, 8.0F, -2.0F);
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, -6.0F, 6.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(15.0), (float)Math.toRadians(12.5), (float)Math.toRadians(2.5));
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-12.5), 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, 8.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, -6.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(8);
      this.animator.startKeyframe(4);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(5.0), 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(2.5), (float)Math.toRadians(-10.0), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(2.5), (float)Math.toRadians(45.0), (float)Math.toRadians(-12.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-20.0), (float)Math.toRadians(-30.0), (float)Math.toRadians(-25.0));
      this.animator.move(this.left_arm, 0.0F, -2.0F, -2.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-75.0), (float)Math.toRadians(25.0), 0.0F);
      this.animator.move(this.left_arm2, 0.0F, -2.0F, 2.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(32.5), (float)Math.toRadians(-7.5), (float)Math.toRadians(57.5));
      this.animator.move(this.right_arm, -4.0F, 8.0F, 2.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(-5.0), (float)Math.toRadians(-25.0), (float)Math.toRadians(12.5));
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-12.5), 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, 8.0F);
      this.animator.move(this.right_leg, 0.0F, 0.0F, -6.0F);
      this.animator.endKeyframe();
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_BLACKHOLE);
      this.animator.startKeyframe(12);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(42.5), 0.0F);
      this.animator.rotate(this.lowerbody, 0.0F, (float)Math.toRadians(2.5), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-12.5), (float)Math.toRadians(22.5), (float)Math.toRadians(-10.0));
      this.animator.move(this.right_leg, 0.0F, 0.0F, 9.0F);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-35.0), 0.0F);
      this.animator.move(this.left_leg, 0.0F, -7.0F, -9.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-70.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(55.0));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-65.0), 0.0F, (float)Math.toRadians(-57.5));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, 6.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(-5.0), (float)Math.toRadians(-32.5), 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(12);
      this.animator.startKeyframe(3);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(42.5), 0.0F);
      this.animator.rotate(this.lowerbody, 0.0F, (float)Math.toRadians(5.0), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(17.5), (float)Math.toRadians(20.0), (float)Math.toRadians(10.0));
      this.animator.move(this.right_leg, 0.0F, 0.0F, 9.0F);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-30.0), 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -9.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(30.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(62.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-32.5), 0.0F, (float)Math.toRadians(-50.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, 6.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(-5.0), (float)Math.toRadians(-32.5), 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(20);
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Ender_Guardian_Entity.GUARDIAN_ROCKETPUNCH);
      this.animator.startKeyframe(0);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(42.5), 0.0F);
      this.animator.rotate(this.lowerbody, 0.0F, (float)Math.toRadians(5.0), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(17.5), (float)Math.toRadians(20.0), (float)Math.toRadians(10.0));
      this.animator.move(this.right_leg, 0.0F, 0.0F, 9.0F);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-30.0), 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -9.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(30.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(62.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-32.5), 0.0F, (float)Math.toRadians(-50.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, 6.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(-5.0), (float)Math.toRadians(-32.5), 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(42.5), 0.0F);
      this.animator.rotate(this.lowerbody, 0.0F, (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(17.5), (float)Math.toRadians(25.0), (float)Math.toRadians(10.0));
      this.animator.move(this.right_leg, 0.0F, 0.0F, 13.0F);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-35.0), 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -9.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(40.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(62.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-57.5), 0.0F, (float)Math.toRadians(-55.0));
      this.animator.rotate(this.right_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.right_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(-5.0), (float)Math.toRadians(-32.5), 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(3);
      this.animator.rotate(this.root, 0.0F, (float)Math.toRadians(-52.5), 0.0F);
      this.animator.rotate(this.lowerbody, 0.0F, (float)Math.toRadians(-20.0), 0.0F);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(12.5), 0.0F, (float)Math.toRadians(-12.5));
      this.animator.move(this.right_leg, 0.0F, 0.0F, 13.0F);
      this.animator.rotate(this.left_leg, 0.0F, (float)Math.toRadians(-35.0), 0.0F);
      this.animator.move(this.left_leg, 0.0F, 0.0F, -9.0F);
      this.animator.rotate(this.right_arm, (float)Math.toRadians(-27.5), (float)Math.toRadians(-2.5), (float)Math.toRadians(72.5));
      this.animator.rotate(this.left_arm, (float)Math.toRadians(-10.0), (float)Math.toRadians(-10.0), (float)Math.toRadians(-62.5));
      this.animator.move(this.right_arm, -4.0F, 0.0F, 0.0F);
      this.animator.rotate(this.left_arm2, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.left_arm2, 0.0F, 6.0F, 6.0F);
      this.animator.rotate(this.helmet, (float)Math.toRadians(-10.0), (float)Math.toRadians(32.5), 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(15);
      this.animator.resetKeyframe(15);
   }

   public void setupAnim(Ender_Guardian_Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
      this.animate(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch);
      float walkSpeed = 0.5F;
      float walkDegree = 0.5F;
      this.faceTarget(netHeadYaw, headPitch, 1.0F, new AdvancedModelBox[]{this.helmet});
      this.walk(this.left_leg, walkSpeed, walkDegree * 1.2F, true, 0.0F, 0.0F, limbSwing, limbSwingAmount);
      this.flap(this.root, walkSpeed, walkDegree * 0.2F, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
      this.walk(this.right_leg, walkSpeed, walkDegree * 1.2F, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
      this.walk(this.left_arm, walkSpeed, walkDegree * 1.2F, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
      this.walk(this.right_arm, walkSpeed, walkDegree * 1.2F, true, 0.0F, 0.0F, limbSwing, limbSwingAmount);
      this.upperhelmet.showModel = !entityIn.getIsHelmetless();
      this.head.showModel = entityIn.f_20919_ <= 100;
   }

   public Iterable<AdvancedModelBox> getAllParts() {
      return ImmutableList.of(
         this.root,
         this.left_arm,
         this.right_arm,
         this.left_arm2,
         this.right_arm2,
         this.left_fist,
         this.right_fist,
         this.left_leg,
         this.right_leg,
         this.head,
         this.armor,
         this.helmet,
         new AdvancedModelBox[]{this.upperhelmet, this.lowerbody, this.upperbody, this.rightarmor, this.leftarmor}
      );
   }

   public Iterable<BasicModelPart> parts() {
      return ImmutableList.of(this.root);
   }

   public void setRotationAngle(AdvancedModelBox AdvancedModelBox, float x, float y, float z) {
      AdvancedModelBox.rotateAngleX = x;
      AdvancedModelBox.rotateAngleY = y;
      AdvancedModelBox.rotateAngleZ = z;
   }
}
