package com.github.L_Ender.cataclysm.client.model.entity;

import com.github.L_Ender.cataclysm.entity.AnimationMonster.BossMonsters.Old_Netherite_Monstrosity_Entity;
import com.github.L_Ender.lionfishapi.client.model.Animations.ModelAnimator;
import com.github.L_Ender.lionfishapi.client.model.tools.AdvancedEntityModel;
import com.github.L_Ender.lionfishapi.client.model.tools.AdvancedModelBox;
import com.github.L_Ender.lionfishapi.client.model.tools.BasicModelPart;
import com.github.L_Ender.lionfishapi.server.animation.IAnimatedEntity;
import com.google.common.collect.ImmutableList;
import net.minecraft.client.Minecraft;

public class Old_Netherite_Monstrosity_Model extends AdvancedEntityModel<Old_Netherite_Monstrosity_Entity> {
   private final AdvancedModelBox root;
   private final AdvancedModelBox lowerbody;
   private final AdvancedModelBox upperbody;
   public final AdvancedModelBox head;
   private final AdvancedModelBox horns;
   private final AdvancedModelBox jaw;
   private final AdvancedModelBox leftarmjoint;
   private final AdvancedModelBox leftarm;
   private final AdvancedModelBox leftarm2;
   private final AdvancedModelBox lefthand;
   private final AdvancedModelBox leftfinger1;
   private final AdvancedModelBox leftfinger2;
   private final AdvancedModelBox leftfinger3;
   private final AdvancedModelBox rightarmjoint;
   private final AdvancedModelBox rightarm;
   private final AdvancedModelBox rightarm2;
   private final AdvancedModelBox righthand;
   private final AdvancedModelBox rightfinger1;
   private final AdvancedModelBox rightfinger2;
   private final AdvancedModelBox rightfinger3;
   private final AdvancedModelBox rightleg;
   private final AdvancedModelBox leftleg;
   private ModelAnimator animator;

   public Old_Netherite_Monstrosity_Model() {
      this.texWidth = 512;
      this.texHeight = 512;
      this.root = new AdvancedModelBox(this);
      this.root.setRotationPoint(0.0F, 24.0F, 0.0F);
      this.lowerbody = new AdvancedModelBox(this);
      this.lowerbody.setRotationPoint(0.0F, -24.0F, 2.0F);
      this.root.addChild(this.lowerbody);
      this.lowerbody.setTextureOffset(175, 193).addBox(-14.0F, -11.0F, -10.5F, 28.0F, 11.0F, 21.0F, 0.0F, false);
      this.upperbody = new AdvancedModelBox(this);
      this.upperbody.setRotationPoint(0.0F, -11.0F, 0.0F);
      this.lowerbody.addChild(this.upperbody);
      this.upperbody.setTextureOffset(0, 0).addBox(-37.0F, -57.0F, -15.0F, 74.0F, 57.0F, 30.0F, 0.0F, false);
      this.upperbody.setTextureOffset(209, 226).addBox(-14.0F, -51.0F, 15.0F, 28.0F, 16.0F, 11.0F, 0.0F, false);
      this.head = new AdvancedModelBox(this);
      this.head.setRotationPoint(0.0F, -33.0F, -15.5F);
      this.upperbody.addChild(this.head);
      this.head.setTextureOffset(0, 139).addBox(-14.0F, -18.0F, -20.5F, 28.0F, 31.0F, 22.0F, 0.0F, false);
      this.head.setTextureOffset(246, 112).addBox(-34.0F, -12.5F, -16.0F, 20.0F, 13.0F, 13.0F, 0.0F, false);
      this.head.setTextureOffset(246, 112).addBox(14.0F, -12.5F, -16.0F, 20.0F, 13.0F, 13.0F, 0.0F, true);
      this.head.setTextureOffset(253, 184).addBox(-34.0F, -27.5F, -16.0F, 8.0F, 15.0F, 13.0F, 0.0F, false);
      this.head.setTextureOffset(169, 171).addBox(26.0F, -15.5F, -16.0F, 8.0F, 3.0F, 13.0F, 0.0F, false);
      this.head.setTextureOffset(12, 0).addBox(-3.0F, -2.0F, -20.7F, 6.0F, 3.0F, 1.0F, 0.0F, false);
      this.head.setTextureOffset(17, 5).addBox(-14.25F, 1.5F, -20.7F, 4.0F, 4.0F, 1.0F, 0.0F, false);
      this.head.setTextureOffset(17, 5).addBox(10.25F, 1.5F, -20.7F, 4.0F, 4.0F, 1.0F, 0.0F, false);
      this.horns = new AdvancedModelBox(this);
      this.horns.setRotationPoint(-4.5F, 47.0F, -3.5F);
      this.head.addChild(this.horns);
      this.setRotationAngle(this.horns, 1.0472F, 0.0F, 0.0F);
      this.jaw = new AdvancedModelBox(this);
      this.jaw.setRotationPoint(0.0F, 12.0F, 0.5F);
      this.head.addChild(this.jaw);
      this.setRotationAngle(this.jaw, 0.0F, 0.0F, 0.0F);
      this.jaw.setTextureOffset(209, 0).addBox(-13.5F, -5.0F, -20.9F, 27.0F, 10.0F, 21.0F, 0.0F, false);
      this.jaw.setTextureOffset(209, 32).addBox(-13.5F, 2.0F, -20.9F, 27.0F, 0.0F, 21.0F, 0.0F, false);
      this.leftarmjoint = new AdvancedModelBox(this);
      this.leftarmjoint.setRotationPoint(37.0F, -38.5F, -2.5F);
      this.upperbody.addChild(this.leftarmjoint);
      this.leftarm = new AdvancedModelBox(this);
      this.leftarm.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.leftarmjoint.addChild(this.leftarm);
      this.leftarm.setTextureOffset(101, 163).addBox(0.0F, -33.5F, -13.5F, 20.0F, 23.0F, 27.0F, 0.0F, false);
      this.leftarm.setTextureOffset(0, 88).addBox(0.0F, -10.5F, -13.5F, 37.0F, 23.0F, 27.0F, 0.0F, false);
      this.leftarm2 = new AdvancedModelBox(this);
      this.leftarm2.setRotationPoint(18.0F, 12.0F, 0.0F);
      this.leftarm.addChild(this.leftarm2);
      this.setRotationAngle(this.leftarm2, -0.1309F, 0.0F, 0.0F);
      this.leftarm2.setTextureOffset(132, 226).addBox(-11.0F, -4.5F, -8.0F, 22.0F, 22.0F, 16.0F, 0.0F, false);
      this.lefthand = new AdvancedModelBox(this);
      this.lefthand.setRotationPoint(0.0F, 17.0F, 0.0F);
      this.leftarm2.addChild(this.lefthand);
      this.setRotationAngle(this.lefthand, -0.0873F, 0.0F, 0.0F);
      this.lefthand.setTextureOffset(57, 214).addBox(-15.0F, 0.0F, -15.0F, 7.0F, 20.0F, 30.0F, 0.0F, false);
      this.lefthand.setTextureOffset(201, 133).addBox(8.0F, 0.0F, -15.0F, 7.0F, 20.0F, 30.0F, 0.0F, false);
      this.lefthand.setTextureOffset(250, 54).addBox(-8.0F, 0.0F, 8.0F, 16.0F, 20.0F, 7.0F, 0.0F, false);
      this.lefthand.setTextureOffset(0, 242).addBox(-8.0F, 0.0F, -15.0F, 16.0F, 20.0F, 7.0F, 0.0F, false);
      this.lefthand.setTextureOffset(102, 88).addBox(-8.0F, 17.0F, -8.0F, 16.0F, 2.0F, 16.0F, 0.0F, false);
      this.lefthand.setTextureOffset(246, 139).addBox(-8.0F, 0.0F, -8.0F, 16.0F, 0.0F, 16.0F, 0.0F, false);
      this.leftfinger1 = new AdvancedModelBox(this);
      this.leftfinger1.setRotationPoint(10.0F, 20.0F, 6.0F);
      this.lefthand.addChild(this.leftfinger1);
      this.leftfinger1.setTextureOffset(0, 0).addBox(-1.5F, -2.5F, -1.5F, 3.0F, 15.0F, 5.0F, 0.0F, false);
      this.leftfinger2 = new AdvancedModelBox(this);
      this.leftfinger2.setRotationPoint(10.0F, 20.0F, -8.0F);
      this.lefthand.addChild(this.leftfinger2);
      this.leftfinger2.setTextureOffset(0, 0).addBox(-1.5F, -2.5F, -1.5F, 3.0F, 15.0F, 5.0F, 0.0F, false);
      this.leftfinger3 = new AdvancedModelBox(this);
      this.leftfinger3.setRotationPoint(-10.0F, 20.0F, -1.5F);
      this.lefthand.addChild(this.leftfinger3);
      this.leftfinger3.setTextureOffset(0, 0).addBox(-1.5F, -2.5F, -1.5F, 3.0F, 15.0F, 5.0F, 0.0F, false);
      this.rightarmjoint = new AdvancedModelBox(this);
      this.rightarmjoint.setRotationPoint(-37.0F, -38.5F, -2.5F);
      this.upperbody.addChild(this.rightarmjoint);
      this.rightarm = new AdvancedModelBox(this);
      this.rightarm.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.rightarmjoint.addChild(this.rightarm);
      this.rightarm.setTextureOffset(182, 61).addBox(-20.0F, -33.5F, -13.5F, 20.0F, 23.0F, 27.0F, 0.0F, false);
      this.rightarm.setTextureOffset(102, 112).addBox(-37.0F, -10.5F, -13.5F, 37.0F, 23.0F, 27.0F, 0.0F, false);
      this.rightarm2 = new AdvancedModelBox(this);
      this.rightarm2.setRotationPoint(-19.0F, 12.0F, 0.0F);
      this.rightarm.addChild(this.rightarm2);
      this.setRotationAngle(this.rightarm2, -0.1309F, 0.0F, 0.0F);
      this.rightarm2.setTextureOffset(132, 226).addBox(-11.0F, -4.5F, -8.0F, 22.0F, 22.0F, 16.0F, 0.0F, false);
      this.righthand = new AdvancedModelBox(this);
      this.righthand.setRotationPoint(0.0F, 17.0F, 0.0F);
      this.rightarm2.addChild(this.righthand);
      this.setRotationAngle(this.righthand, -0.0873F, 0.0F, 0.0F);
      this.righthand.setTextureOffset(57, 214).addBox(-15.0F, 0.0F, -15.0F, 7.0F, 20.0F, 30.0F, 0.0F, false);
      this.righthand.setTextureOffset(201, 133).addBox(8.0F, 0.0F, -15.0F, 7.0F, 20.0F, 30.0F, 0.0F, false);
      this.righthand.setTextureOffset(250, 54).addBox(-8.0F, 0.0F, 8.0F, 16.0F, 20.0F, 7.0F, 0.0F, false);
      this.righthand.setTextureOffset(0, 242).addBox(-8.0F, 0.0F, -15.0F, 16.0F, 20.0F, 7.0F, 0.0F, false);
      this.righthand.setTextureOffset(102, 88).addBox(-8.0F, 17.0F, -8.0F, 16.0F, 2.0F, 16.0F, 0.0F, false);
      this.righthand.setTextureOffset(246, 139).addBox(-8.0F, 0.0F, -8.0F, 16.0F, 0.0F, 16.0F, 0.0F, false);
      this.rightfinger1 = new AdvancedModelBox(this);
      this.rightfinger1.setRotationPoint(-10.0F, 20.0F, 6.0F);
      this.righthand.addChild(this.rightfinger1);
      this.rightfinger1.setTextureOffset(0, 0).addBox(-1.5F, -2.5F, -1.5F, 3.0F, 15.0F, 5.0F, 0.0F, false);
      this.rightfinger2 = new AdvancedModelBox(this);
      this.rightfinger2.setRotationPoint(-10.0F, 20.0F, -8.0F);
      this.righthand.addChild(this.rightfinger2);
      this.rightfinger2.setTextureOffset(0, 0).addBox(-1.5F, -2.5F, -1.5F, 3.0F, 15.0F, 5.0F, 0.0F, false);
      this.rightfinger3 = new AdvancedModelBox(this);
      this.rightfinger3.setRotationPoint(10.0F, 20.0F, -1.5F);
      this.righthand.addChild(this.rightfinger3);
      this.rightfinger3.setTextureOffset(0, 0).addBox(-1.5F, -2.5F, -1.5F, 3.0F, 15.0F, 5.0F, 0.0F, false);
      this.rightleg = new AdvancedModelBox(this);
      this.rightleg.setRotationPoint(-14.0F, -27.0F, 0.0F);
      this.root.addChild(this.rightleg);
      this.rightleg.setTextureOffset(0, 193).addBox(-19.0F, -2.0F, -9.5F, 24.0F, 29.0F, 19.0F, 0.0F, false);
      this.leftleg = new AdvancedModelBox(this);
      this.leftleg.setRotationPoint(14.0F, -27.0F, 0.0F);
      this.root.addChild(this.leftleg);
      this.leftleg.setTextureOffset(0, 193).addBox(-5.0F, -2.0F, -9.5F, 24.0F, 29.0F, 19.0F, 0.0F, true);
      this.animator = ModelAnimator.create();
      this.updateDefaultPose();
   }

   public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4) {
      this.resetToDefaultPose();
      this.animator.update(entity);
      this.animator.setAnimation(Old_Netherite_Monstrosity_Entity.MONSTROSITY_CHARGE);
      this.animator.startKeyframe(15);
      this.animator.move(this.rightarm, -11.0F, -5.0F, 0.0F);
      this.animator.rotate(this.rightarm, 0.0F, (float)Math.toRadians(-90.0), 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.move(this.leftarm, 11.0F, -5.0F, 0.0F);
      this.animator.rotate(this.leftarm, 0.0F, (float)Math.toRadians(90.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(15);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftleg, (float)Math.toRadians(65.0), 0.0F, 0.0F);
      this.animator.move(this.leftleg, 0.0F, 7.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
      this.animator.move(this.rightarm, -11.0F, 15.0F, 0.0F);
      this.animator.rotate(this.rightarmjoint, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm, 0.0F, (float)Math.toRadians(-90.0), 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.move(this.leftarm, 11.0F, 15.0F, 0.0F);
      this.animator.rotate(this.leftarmjoint, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, 0.0F, (float)Math.toRadians(90.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(12);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(50.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftleg, (float)Math.toRadians(65.0), 0.0F, 0.0F);
      this.animator.move(this.leftleg, 0.0F, 7.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.move(this.rightarm, -11.0F, 15.0F, 0.0F);
      this.animator.move(this.righthand, 0.0F, -10.0F, 0.0F);
      this.animator.rotate(this.rightarmjoint, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm, 0.0F, (float)Math.toRadians(-90.0), 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.move(this.leftarm, 11.0F, 15.0F, 0.0F);
      this.animator.move(this.lefthand, 0.0F, -10.0F, 0.0F);
      this.animator.rotate(this.leftarmjoint, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, 0.0F, (float)Math.toRadians(90.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(15);
      this.animator.startKeyframe(10);
      this.animator.move(this.rightarm, -11.0F, -5.0F, 0.0F);
      this.animator.rotate(this.rightarm, 0.0F, (float)Math.toRadians(-90.0), 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.move(this.leftarm, 11.0F, -5.0F, 0.0F);
      this.animator.rotate(this.leftarm, 0.0F, (float)Math.toRadians(90.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.resetKeyframe(10);
      this.animator.setAnimation(Old_Netherite_Monstrosity_Entity.MONSTROSITY_ERUPTIONATTACK);
      this.animator.startKeyframe(10);
      this.animator.move(this.rightarm, -11.0F, -5.0F, -4.0F);
      this.animator.rotate(this.rightarm, 0.0F, (float)Math.toRadians(90.0), 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.move(this.leftarm, 11.0F, -5.0F, -4.0F);
      this.animator.rotate(this.leftarm, 0.0F, (float)Math.toRadians(-90.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(5);
      this.animator.startKeyframe(8);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.move(this.rightarm, -11.0F, 13.0F, -4.0F);
      this.animator.move(this.rightarm2, 0.0F, 4.0F, 0.0F);
      this.animator.rotate(this.rightarmjoint, (float)Math.toRadians(40.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm, 0.0F, (float)Math.toRadians(90.0), 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.move(this.leftarm, 11.0F, 13.0F, -4.0F);
      this.animator.move(this.leftarm2, 0.0F, 4.0F, 0.0F);
      this.animator.rotate(this.leftarmjoint, (float)Math.toRadians(40.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, 0.0F, (float)Math.toRadians(-90.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(5);
      this.animator.startKeyframe(6);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-70.0), 0.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.rotate(this.jaw, (float)Math.toRadians(67.5), 0.0F, 0.0F);
      this.animator.move(this.rightarm, -11.0F, 12.0F, -14.0F);
      this.animator.move(this.rightarm2, 0.0F, -9.0F, 0.0F);
      this.animator.rotate(this.rightarmjoint, (float)Math.toRadians(70.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm, 0.0F, (float)Math.toRadians(90.0), 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.move(this.leftarm, 11.0F, 12.0F, -14.0F);
      this.animator.move(this.leftarm2, 0.0F, -9.0F, 0.0F);
      this.animator.rotate(this.leftarmjoint, (float)Math.toRadians(70.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, 0.0F, (float)Math.toRadians(-90.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(6);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.move(this.rightarm, -11.0F, 12.0F, -4.0F);
      this.animator.move(this.rightarm2, 0.0F, 4.0F, 0.0F);
      this.animator.rotate(this.rightarmjoint, (float)Math.toRadians(40.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm, 0.0F, (float)Math.toRadians(90.0), 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.move(this.leftarm, 11.0F, 12.0F, -4.0F);
      this.animator.move(this.leftarm2, 0.0F, 4.0F, 0.0F);
      this.animator.rotate(this.leftarmjoint, (float)Math.toRadians(40.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, 0.0F, (float)Math.toRadians(-90.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(5.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Old_Netherite_Monstrosity_Entity.MONSTROSITY_EARTHQUAKE);
      this.animator.startKeyframe(20);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
      this.animator.rotate(this.jaw, (float)Math.toRadians(25.0), 0.0F, 0.0F);
      this.animator.move(this.rightleg, 0.0F, -6.0F, -6.0F);
      this.animator.rotate(this.leftleg, 0.0F, (float)Math.toRadians(-25.0), 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-160.0), (float)Math.toRadians(20.0), (float)Math.toRadians(-10.0));
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-160.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(10.0));
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-20.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-20.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(40.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftleg, (float)Math.toRadians(65.0), 0.0F, 0.0F);
      this.animator.move(this.leftleg, 0.0F, 7.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-100.0), (float)Math.toRadians(20.0), (float)Math.toRadians(-10.0));
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-100.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(10.0));
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(15);
      this.animator.resetKeyframe(25);
      this.animator.setAnimation(Old_Netherite_Monstrosity_Entity.MONSTROSITY_EARTHQUAKE2);
      this.animator.startKeyframe(13);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
      this.animator.rotate(this.jaw, (float)Math.toRadians(25.0), 0.0F, 0.0F);
      this.animator.move(this.rightleg, 0.0F, -6.0F, -6.0F);
      this.animator.rotate(this.leftleg, 0.0F, (float)Math.toRadians(-25.0), 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-160.0), (float)Math.toRadians(20.0), (float)Math.toRadians(-10.0));
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-160.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(10.0));
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-20.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-20.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(7);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(40.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftleg, (float)Math.toRadians(65.0), 0.0F, 0.0F);
      this.animator.move(this.leftleg, 0.0F, 7.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-100.0), (float)Math.toRadians(20.0), (float)Math.toRadians(-10.0));
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-100.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(10.0));
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(15);
      this.animator.resetKeyframe(25);
      this.animator.setAnimation(Old_Netherite_Monstrosity_Entity.MONSTROSITY_EARTHQUAKE3);
      this.animator.startKeyframe(16);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
      this.animator.rotate(this.jaw, (float)Math.toRadians(25.0), 0.0F, 0.0F);
      this.animator.move(this.rightleg, 0.0F, -6.0F, -6.0F);
      this.animator.rotate(this.leftleg, 0.0F, (float)Math.toRadians(-25.0), 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-160.0), (float)Math.toRadians(20.0), (float)Math.toRadians(-10.0));
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-160.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(10.0));
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-20.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-20.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(9);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(40.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftleg, (float)Math.toRadians(65.0), 0.0F, 0.0F);
      this.animator.move(this.leftleg, 0.0F, 7.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-100.0), (float)Math.toRadians(20.0), (float)Math.toRadians(-10.0));
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-100.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(10.0));
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(15);
      this.animator.resetKeyframe(25);
      this.animator.setAnimation(Old_Netherite_Monstrosity_Entity.MONSTROSITY_BERSERK);
      this.animator.startKeyframe(16);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
      this.animator.move(this.rightleg, 0.0F, -6.0F, -6.0F);
      this.animator.rotate(this.leftleg, 0.0F, (float)Math.toRadians(-25.0), 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-160.0), 0.0F, (float)Math.toRadians(-5.0));
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-160.0), 0.0F, (float)Math.toRadians(5.0));
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-20.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-20.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(9);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(15.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.move(this.head, 0.0F, -3.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
      this.animator.move(this.leftarm, 0.0F, 7.0F, -15.0F);
      this.animator.move(this.rightarm, 0.0F, 7.0F, -15.0F);
      this.animator.move(this.leftarm2, 0.0F, 3.0F, 0.0F);
      this.animator.move(this.rightarm2, 0.0F, 3.0F, 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(10);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(15.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-50.0), (float)Math.toRadians(-10.0), (float)Math.toRadians(10.0));
      this.animator.rotate(this.jaw, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.move(this.leftarm, 0.0F, 7.0F, -15.0F);
      this.animator.move(this.rightarm, 0.0F, 7.0F, -15.0F);
      this.animator.move(this.leftarm2, 0.0F, 3.0F, 0.0F);
      this.animator.move(this.rightarm2, 0.0F, 3.0F, 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(10);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(15.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-50.0), (float)Math.toRadians(10.0), (float)Math.toRadians(-10.0));
      this.animator.rotate(this.jaw, (float)Math.toRadians(32.5), 0.0F, 0.0F);
      this.animator.move(this.leftarm, 0.0F, 7.0F, -15.0F);
      this.animator.move(this.rightarm, 0.0F, 7.0F, -15.0F);
      this.animator.move(this.leftarm2, 0.0F, 3.0F, 0.0F);
      this.animator.move(this.rightarm2, 0.0F, 3.0F, 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(5);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(15.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.move(this.head, 0.0F, -3.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
      this.animator.rotate(this.jaw, (float)Math.toRadians(22.5), 0.0F, 0.0F);
      this.animator.move(this.leftarm, 0.0F, 7.0F, -15.0F);
      this.animator.move(this.rightarm, 0.0F, 7.0F, -15.0F);
      this.animator.move(this.leftarm2, 0.0F, 3.0F, 0.0F);
      this.animator.move(this.rightarm2, 0.0F, 3.0F, 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(5);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(15.0), 0.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(30.0), 0.0F, 0.0F);
      this.animator.move(this.head, 0.0F, -3.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.move(this.leftarm, 0.0F, 7.0F, -15.0F);
      this.animator.move(this.rightarm, 0.0F, 7.0F, -15.0F);
      this.animator.move(this.leftarm2, 0.0F, 3.0F, 0.0F);
      this.animator.move(this.rightarm2, 0.0F, 3.0F, 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(5);
      this.animator.resetKeyframe(15);
      this.animator.setAnimation(Old_Netherite_Monstrosity_Entity.MONSTROSITY_DEATH);
      this.animator.startKeyframe(7);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), (float)Math.toRadians(-10.0), 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-10.0), (float)Math.toRadians(-30.0), 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-10.0), (float)Math.toRadians(30.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, 0.0F, (float)Math.toRadians(-25.0), 0.0F);
      this.animator.rotate(this.lefthand, 0.0F, (float)Math.toRadians(25.0), 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-5.0), (float)Math.toRadians(-20.0), 0.0F);
      this.animator.rotate(this.jaw, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(7);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-10.0), (float)Math.toRadians(-30.0), 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-10.0), (float)Math.toRadians(30.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, 0.0F, (float)Math.toRadians(-25.0), 0.0F);
      this.animator.rotate(this.lefthand, 0.0F, (float)Math.toRadians(25.0), 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-5.0), (float)Math.toRadians(20.0), 0.0F);
      this.animator.rotate(this.jaw, (float)Math.toRadians(27.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(7);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), (float)Math.toRadians(-10.0), 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-10.0), (float)Math.toRadians(-30.0), 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-10.0), (float)Math.toRadians(30.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, 0.0F, (float)Math.toRadians(-25.0), 0.0F);
      this.animator.rotate(this.lefthand, 0.0F, (float)Math.toRadians(25.0), 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-5.0), (float)Math.toRadians(-20.0), 0.0F);
      this.animator.rotate(this.jaw, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(7);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-10.0), (float)Math.toRadians(-30.0), 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-10.0), (float)Math.toRadians(30.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, 0.0F, (float)Math.toRadians(-25.0), 0.0F);
      this.animator.rotate(this.lefthand, 0.0F, (float)Math.toRadians(25.0), 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-5.0), (float)Math.toRadians(20.0), 0.0F);
      this.animator.rotate(this.jaw, (float)Math.toRadians(27.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(7);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), (float)Math.toRadians(-10.0), 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-10.0), (float)Math.toRadians(-30.0), 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-10.0), (float)Math.toRadians(30.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, 0.0F, (float)Math.toRadians(-25.0), 0.0F);
      this.animator.rotate(this.lefthand, 0.0F, (float)Math.toRadians(25.0), 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-5.0), (float)Math.toRadians(-10.0), 0.0F);
      this.animator.rotate(this.jaw, (float)Math.toRadians(17.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(7);
      this.animator.rotate(this.upperbody, (float)Math.toRadians(-5.0), (float)Math.toRadians(10.0), 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-10.0), (float)Math.toRadians(-30.0), 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-10.0), (float)Math.toRadians(30.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, 0.0F, (float)Math.toRadians(-25.0), 0.0F);
      this.animator.rotate(this.lefthand, 0.0F, (float)Math.toRadians(25.0), 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(-5.0), (float)Math.toRadians(20.0), 0.0F);
      this.animator.rotate(this.jaw, (float)Math.toRadians(27.5), 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(8);
      this.animator.rotate(this.root, (float)Math.toRadians(-35.0), 0.0F, 0.0F);
      this.animator.move(this.root, 0.0F, -5.0F, 0.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(40.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftleg, (float)Math.toRadians(35.0), 0.0F, 0.0F);
      this.animator.rotate(this.jaw, (float)Math.toRadians(20.0), 0.0F, 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-7.5), (float)Math.toRadians(-35.0), 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-7.5), (float)Math.toRadians(35.0), 0.0F);
      this.animator.rotate(this.leftarm2, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm2, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, 0.0F, (float)Math.toRadians(-25.0), 0.0F);
      this.animator.rotate(this.lefthand, 0.0F, (float)Math.toRadians(25.0), 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(10);
      this.animator.startKeyframe(5);
      this.animator.rotate(this.root, (float)Math.toRadians(-90.0), 0.0F, 0.0F);
      this.animator.move(this.root, 0.0F, -9.0F, 0.0F);
      this.animator.move(this.lowerbody, 0.0F, 0.0F, -3.0F);
      this.animator.rotate(this.lowerbody, (float)Math.toRadians(80.0), 0.0F, 0.0F);
      this.animator.rotate(this.head, (float)Math.toRadians(5.0), 0.0F, (float)Math.toRadians(-7.5));
      this.animator.rotate(this.jaw, (float)Math.toRadians(25.0), 0.0F, 0.0F);
      this.animator.move(this.leftleg, 0.0F, 5.0F, 0.0F);
      this.animator.move(this.rightleg, 0.0F, 5.0F, 0.0F);
      this.animator.rotate(this.leftleg, 0.0F, 0.0F, (float)Math.toRadians(-15.0));
      this.animator.rotate(this.rightleg, 0.0F, 0.0F, (float)Math.toRadians(15.0));
      this.animator.move(this.leftarm, 0.0F, 5.0F, 0.0F);
      this.animator.move(this.rightarm, 0.0F, 5.0F, 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(-15.0), (float)Math.toRadians(-40.0), 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(-15.0), (float)Math.toRadians(40.0), 0.0F);
      this.animator.rotate(this.leftarm, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.rightarm, (float)Math.toRadians(7.5), 0.0F, 0.0F);
      this.animator.rotate(this.righthand, (float)Math.toRadians(-5.0), (float)Math.toRadians(-12.5), 0.0F);
      this.animator.rotate(this.lefthand, (float)Math.toRadians(-5.0), (float)Math.toRadians(12.5), 0.0F);
      this.animator.endKeyframe();
      this.animator.setStaticKeyframe(110);
   }

   public void setupAnim(Old_Netherite_Monstrosity_Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
      this.animate(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch);
      float walkSpeed = 0.35F;
      float walkDegree = 0.5F;
      float jawSpeed = 0.2F;
      this.faceTarget(netHeadYaw, headPitch, 1.0F, new AdvancedModelBox[]{this.head});
      this.walk(this.leftleg, walkSpeed, walkDegree * 1.0F, false, -25.0F, 0.0F, limbSwing, limbSwingAmount);
      this.flap(this.root, walkSpeed, walkDegree * 0.1F, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
      this.walk(this.rightleg, walkSpeed, walkDegree * 1.0F, true, -25.0F, 0.0F, limbSwing, limbSwingAmount);
      float leftLegS = (float)(
         Math.sin((double)(limbSwing * walkSpeed) - 2.5) * (double)limbSwingAmount * (double)walkDegree - (double)(limbSwingAmount * walkDegree)
      );
      float rightLegS = (float)(
         Math.sin(-((double)(limbSwing * walkSpeed)) + 2.5) * (double)limbSwingAmount * (double)walkDegree - (double)(limbSwingAmount * walkDegree)
      );
      this.leftleg.rotationPointY += 6.0F * leftLegS;
      this.rightleg.rotationPointY += 6.0F * rightLegS;
      this.leftleg.rotationPointZ += 8.0F * leftLegS;
      this.rightleg.rotationPointZ += 8.0F * rightLegS;
      this.walk(this.leftarm, walkSpeed, walkDegree * 0.5F, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
      this.walk(this.rightarm, walkSpeed, walkDegree * 0.5F, true, 0.0F, 0.0F, limbSwing, limbSwingAmount);
      this.walk(this.jaw, jawSpeed, walkDegree * 0.8F, true, 0.0F, -0.4F, limbSwing, limbSwingAmount);
      float partialTick = Minecraft.m_91087_().m_91296_();
      float deactivateProgress = entityIn.prevdeactivateProgress + (entityIn.deactivateProgress - entityIn.prevdeactivateProgress) * partialTick;
      this.progressRotationPrev(this.lowerbody, deactivateProgress, (float)Math.toRadians(50.0), 0.0F, 0.0F, 40.0F);
      this.progressRotationPrev(this.leftleg, deactivateProgress, (float)Math.toRadians(65.0), 0.0F, 0.0F, 40.0F);
      this.progressPositionPrev(this.leftleg, deactivateProgress, 0.0F, 7.0F, 0.0F, 40.0F);
      this.progressRotationPrev(this.jaw, deactivateProgress, (float)Math.toRadians(-7.5), 0.0F, 0.0F, 40.0F);
      this.progressPositionPrev(this.rightarm, deactivateProgress, -11.0F, 15.0F, 0.0F, 40.0F);
      this.progressPositionPrev(this.righthand, deactivateProgress, 0.0F, -10.0F, 0.0F, 40.0F);
      this.progressRotationPrev(this.rightarmjoint, deactivateProgress, (float)Math.toRadians(-50.0), 0.0F, 0.0F, 40.0F);
      this.progressRotationPrev(this.rightarm, deactivateProgress, 0.0F, (float)Math.toRadians(-90.0), 0.0F, 40.0F);
      this.progressRotationPrev(this.rightarm2, deactivateProgress, (float)Math.toRadians(7.5), 0.0F, 0.0F, 40.0F);
      this.progressRotationPrev(this.righthand, deactivateProgress, (float)Math.toRadians(5.0), 0.0F, 0.0F, 40.0F);
      this.progressPositionPrev(this.leftarm, deactivateProgress, 11.0F, 15.0F, 0.0F, 40.0F);
      this.progressPositionPrev(this.lefthand, deactivateProgress, 0.0F, -10.0F, 0.0F, 40.0F);
      this.progressRotationPrev(this.leftarmjoint, deactivateProgress, (float)Math.toRadians(-50.0), 0.0F, 0.0F, 40.0F);
      this.progressRotationPrev(this.leftarm, deactivateProgress, 0.0F, (float)Math.toRadians(90.0), 0.0F, 40.0F);
      this.progressRotationPrev(this.leftarm2, deactivateProgress, (float)Math.toRadians(7.5), 0.0F, 0.0F, 40.0F);
      this.progressRotationPrev(this.lefthand, deactivateProgress, (float)Math.toRadians(5.0), 0.0F, 0.0F, 40.0F);
   }

   public Iterable<AdvancedModelBox> getAllParts() {
      return ImmutableList.of(
         this.root,
         this.leftarmjoint,
         this.rightarmjoint,
         this.leftarm,
         this.rightarm,
         this.leftarm2,
         this.rightarm2,
         this.lefthand,
         this.righthand,
         this.leftfinger1,
         this.rightfinger1,
         this.leftfinger2,
         new AdvancedModelBox[]{
            this.rightfinger2, this.leftfinger3, this.rightfinger3, this.leftleg, this.rightleg, this.head, this.jaw, this.lowerbody, this.upperbody
         }
      );
   }

   public Iterable<BasicModelPart> parts() {
      return ImmutableList.of(this.root);
   }

   public void setRotationAngle(AdvancedModelBox AdvancedModelBox, float x, float y, float z) {
      AdvancedModelBox.rotateAngleX = x;
      AdvancedModelBox.rotateAngleY = y;
      AdvancedModelBox.rotateAngleZ = z;
   }
}
