modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory

authors="Shadows_of_Fire" #optional

license="MIT License" #mandatory

[[mods]] #mandatory

modId="apotheosis" #mandatory

version="6.5.2" #mandatory

displayName="Apotheosis" #mandatory

description='''All things that should have been'''

[[dependencies.apotheosis]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43.2.14,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="placebo"
    mandatory=true
    versionRange="[7.4.0,)"
    ordering="NONE"
    side="BOTH"